# Generated by Django 4.2.16 on 2025-10-29 19:20

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAnalyticsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم النموذج - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم النموذج - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز النموذج"
                    ),
                ),
                (
                    "analytics_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_PERFORMANCE", "أداء الطلاب"),
                            ("COURSE_ANALYTICS", "تحليلات المقررات"),
                            ("FINANCIAL_FORECAST", "تنبؤات مالية"),
                            ("ENROLLMENT_PREDICTION", "تنبؤات التسجيل"),
                            ("RESOURCE_OPTIMIZATION", "تحسين الموارد"),
                            ("RISK_ASSESSMENT", "تقييم المخاطر"),
                            ("BEHAVIORAL_ANALYSIS", "تحليل السلوك"),
                        ],
                        max_length=25,
                        verbose_name="نوع التحليل",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف النموذج")),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="إعدادات النموذج"),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="معاملات النموذج"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("TRAINING", "تحت التدريب"),
                            ("MAINTENANCE", "صيانة"),
                        ],
                        default="INACTIVE",
                        max_length=15,
                        verbose_name="حالة النموذج",
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="درجة الدقة",
                    ),
                ),
                (
                    "last_training_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر تدريب"
                    ),
                ),
                (
                    "total_predictions",
                    models.IntegerField(default=0, verbose_name="إجمالي التنبؤات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نموذج تحليلات ذكية",
                "verbose_name_plural": "نماذج التحليلات الذكية",
                "ordering": ["analytics_type", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="AIChatBot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الروبوت")),
                (
                    "bot_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_SUPPORT", "دعم طلابي"),
                            ("ACADEMIC_ADVISOR", "مستشار أكاديمي"),
                            ("TECHNICAL_SUPPORT", "دعم تقني"),
                            ("GENERAL_INFO", "معلومات عامة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الروبوت",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف الروبوت")),
                (
                    "personality_traits",
                    models.JSONField(default=dict, verbose_name="سمات الشخصية"),
                ),
                (
                    "knowledge_base",
                    models.JSONField(default=dict, verbose_name="قاعدة المعرفة"),
                ),
                (
                    "response_templates",
                    models.JSONField(default=list, verbose_name="قوالب الرد"),
                ),
                (
                    "total_conversations",
                    models.IntegerField(default=0, verbose_name="إجمالي المحادثات"),
                ),
                (
                    "satisfaction_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="نقاط الرضا",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "روبوت دردشة ذكي",
                "verbose_name_plural": "روبوتات الدردشة الذكية",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم النموذج - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم النموذج - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز النموذج"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف النموذج")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("PREDICTION", "تنبؤي"),
                            ("CLASSIFICATION", "تصنيف"),
                            ("RECOMMENDATION", "توصية"),
                            ("NLP", "معالجة اللغة الطبيعية"),
                            ("COMPUTER_VISION", "رؤية حاسوبية"),
                            ("CLUSTERING", "تجميع"),
                            ("ANOMALY_DETECTION", "كشف الشذوذ"),
                            ("OPTIMIZATION", "تحسين"),
                        ],
                        max_length=20,
                        verbose_name="نوع النموذج",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        max_length=100, verbose_name="الخوارزمية المستخدمة"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="الإصدار"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="معاملات النموذج"),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, verbose_name="معاملات التحكم"),
                ),
                (
                    "feature_columns",
                    models.JSONField(default=list, verbose_name="أعمدة الميزات"),
                ),
                (
                    "target_column",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="العمود المستهدف"
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="دقة النموذج",
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="الدقة",
                    ),
                ),
                (
                    "recall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="الاستدعاء",
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="نتيجة F1",
                    ),
                ),
                (
                    "training_data_size",
                    models.IntegerField(default=0, verbose_name="حجم بيانات التدريب"),
                ),
                (
                    "training_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بداية التدريب"
                    ),
                ),
                (
                    "training_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="نهاية التدريب"
                    ),
                ),
                (
                    "last_retrained",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر إعادة تدريب"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "تحت التدريب"),
                            ("TRAINED", "مُدرب"),
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("DEPRECATED", "مُهمل"),
                            ("FAILED", "فاشل"),
                        ],
                        default="TRAINING",
                        max_length=15,
                        verbose_name="حالة النموذج",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="نشط")),
                (
                    "auto_retrain",
                    models.BooleanField(
                        default=False, verbose_name="إعادة تدريب تلقائي"
                    ),
                ),
                (
                    "retrain_threshold",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.1,
                        max_digits=5,
                        verbose_name="حد إعادة التدريب",
                    ),
                ),
                (
                    "model_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار ملف النموذج"
                    ),
                ),
                (
                    "config_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار ملف الإعدادات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نموذج ذكاء اصطناعي",
                "verbose_name_plural": "نماذج الذكاء الاصطناعي",
                "ordering": ["model_type", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("COURSE", "مقرر"),
                            ("MAJOR", "تخصص"),
                            ("CAREER", "مهنة"),
                            ("STUDY_PLAN", "خطة دراسية"),
                            ("INTERVENTION", "تدخل"),
                            ("IMPROVEMENT", "تحسين"),
                            ("RESOURCE", "مورد"),
                        ],
                        max_length=20,
                        verbose_name="نوع التوصية",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان التوصية"),
                ),
                ("description", models.TextField(verbose_name="وصف التوصية")),
                (
                    "recommendation_data",
                    models.JSONField(default=dict, verbose_name="بيانات التوصية"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="نقاط الثقة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("URGENT", "عاجل"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("ACCEPTED", "مقبول"),
                            ("REJECTED", "مرفوض"),
                            ("IMPLEMENTED", "مُنفذ"),
                            ("EXPIRED", "منتهي"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="صالح حتى"
                    ),
                ),
                (
                    "implemented_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التنفيذ"
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(blank=True, verbose_name="تعليق المستخدم"),
                ),
                (
                    "feedback_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم التوصية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "توصية ذكية",
                "verbose_name_plural": "التوصيات الذكية",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("USER", "مستخدم"),
                            ("BOT", "روبوت"),
                            ("SYSTEM", "نظام"),
                        ],
                        max_length=10,
                        verbose_name="نوع المرسل",
                    ),
                ),
                ("message", models.TextField(verbose_name="نص الرسالة")),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                (
                    "conversation_id",
                    models.CharField(max_length=100, verbose_name="معرف المحادثة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة دردشة",
                "verbose_name_plural": "رسائل الدردشة",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(max_length=100, verbose_name="معرف المحادثة"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("USER", "مستخدم"),
                            ("ASSISTANT", "مساعد"),
                            ("SYSTEM", "نظام"),
                        ],
                        max_length=10,
                        verbose_name="نوع الرسالة",
                    ),
                ),
                ("message_content", models.TextField(verbose_name="محتوى الرسالة")),
                (
                    "message_language",
                    models.CharField(
                        default="ar", max_length=5, verbose_name="لغة الرسالة"
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POSITIVE", "إيجابي"),
                            ("NEGATIVE", "سلبي"),
                            ("NEUTRAL", "محايد"),
                            ("MIXED", "مختلط"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="المشاعر",
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="نقاط المشاعر",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, verbose_name="وقت الرد (ميلي ثانية)"
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="كان مفيداً"
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم المستخدم",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(default=dict, verbose_name="بيانات السياق"),
                ),
                (
                    "intent_detected",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="النية المكتشفة"
                    ),
                ),
                (
                    "entities_extracted",
                    models.JSONField(default=list, verbose_name="الكيانات المستخرجة"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
            ],
            options={
                "verbose_name": "سجل محادثة",
                "verbose_name_plural": "سجلات المحادثات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LearningAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analytics_type",
                    models.CharField(
                        choices=[
                            ("ENGAGEMENT", "التفاعل"),
                            ("PROGRESS", "التقدم"),
                            ("PERFORMANCE", "الأداء"),
                            ("BEHAVIOR", "السلوك"),
                            ("COMPETENCY", "الكفاءة"),
                            ("PREDICTIVE", "تنبؤي"),
                        ],
                        max_length=15,
                        verbose_name="نوع التحليل",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict, verbose_name="البيانات الخام"),
                ),
                (
                    "processed_data",
                    models.JSONField(default=dict, verbose_name="البيانات المعالجة"),
                ),
                ("insights", models.JSONField(default=dict, verbose_name="الرؤى")),
                (
                    "engagement_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نقاط التفاعل",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة التقدم",
                    ),
                ),
                (
                    "mastery_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="مستوى الإتقان",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="التوصيات"),
                ),
                (
                    "action_items",
                    models.JSONField(default=list, verbose_name="عناصر العمل"),
                ),
                (
                    "analysis_period_start",
                    models.DateTimeField(verbose_name="بداية فترة التحليل"),
                ),
                (
                    "analysis_period_end",
                    models.DateTimeField(verbose_name="نهاية فترة التحليل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تحليل تعلم",
                "verbose_name_plural": "تحليلات التعلم",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictiveAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_SUCCESS", "نجاح الطالب"),
                            ("DROPOUT_RISK", "خطر التسرب"),
                            ("ENROLLMENT_FORECAST", "توقع التسجيل"),
                            ("RESOURCE_DEMAND", "طلب الموارد"),
                            ("FINANCIAL_FORECAST", "توقع مالي"),
                            ("PERFORMANCE_TREND", "اتجاه الأداء"),
                            ("CAPACITY_PLANNING", "تخطيط السعة"),
                        ],
                        max_length=30,
                        verbose_name="نوع التنبؤ",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم التحليل")),
                ("description", models.TextField(verbose_name="وصف التحليل")),
                (
                    "target_group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المجموعة المستهدفة"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, verbose_name="البيانات المدخلة"),
                ),
                (
                    "prediction_result",
                    models.JSONField(default=dict, verbose_name="نتيجة التنبؤ"),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="مستوى الثقة",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التنبؤ"
                    ),
                ),
                (
                    "forecast_horizon",
                    models.CharField(max_length=50, verbose_name="أفق التنبؤ"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="صالح حتى"
                    ),
                ),
                (
                    "actual_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="النتيجة الفعلية"
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="نقاط الدقة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تحليل تنبؤي",
                "verbose_name_plural": "التحليلات التنبؤية",
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.CreateModel(
            name="SmartAssistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="اسم المساعد - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, verbose_name="اسم المساعد - إنجليزي"
                    ),
                ),
                (
                    "assistant_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "مساعد طلابي"),
                            ("TEACHER", "مساعد أكاديمي"),
                            ("ADMIN", "مساعد إداري"),
                            ("FINANCIAL", "مساعد مالي"),
                            ("GENERAL", "مساعد عام"),
                        ],
                        max_length=15,
                        verbose_name="نوع المساعد",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(default=list, verbose_name="القدرات"),
                ),
                (
                    "capability_level",
                    models.CharField(
                        choices=[
                            ("BASIC", "أساسي"),
                            ("INTERMEDIATE", "متوسط"),
                            ("ADVANCED", "متقدم"),
                            ("EXPERT", "خبير"),
                        ],
                        default="INTERMEDIATE",
                        max_length=15,
                        verbose_name="مستوى القدرة",
                    ),
                ),
                (
                    "supported_languages",
                    models.JSONField(default=list, verbose_name="اللغات المدعومة"),
                ),
                (
                    "knowledge_base",
                    models.JSONField(default=dict, verbose_name="قاعدة المعرفة"),
                ),
                (
                    "personality_traits",
                    models.JSONField(default=dict, verbose_name="سمات الشخصية"),
                ),
                (
                    "response_style",
                    models.CharField(
                        default="FRIENDLY", max_length=50, verbose_name="أسلوب الرد"
                    ),
                ),
                (
                    "total_interactions",
                    models.IntegerField(default=0, verbose_name="إجمالي التفاعلات"),
                ),
                (
                    "successful_responses",
                    models.IntegerField(default=0, verbose_name="الردود الناجحة"),
                ),
                (
                    "user_satisfaction_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="متوسط رضا المستخدمين",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_learning_enabled",
                    models.BooleanField(default=True, verbose_name="التعلم مُفعل"),
                ),
                (
                    "max_conversation_length",
                    models.IntegerField(
                        default=50, verbose_name="الحد الأقصى للمحادثة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "مساعد ذكي",
                "verbose_name_plural": "المساعدون الأذكياء",
                "ordering": ["assistant_type", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="StudentAIProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "predicted_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="المعدل المتوقع",
                    ),
                ),
                (
                    "graduation_probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="احتمالية التخرج",
                    ),
                ),
                (
                    "dropout_risk",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="خطر التسرب",
                    ),
                ),
                (
                    "academic_standing_prediction",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="التوقع الأكاديمي"
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("VISUAL", "بصري"),
                            ("AUDITORY", "سمعي"),
                            ("KINESTHETIC", "حركي"),
                            ("READING_WRITING", "قراءة وكتابة"),
                            ("MIXED", "مختلط"),
                        ],
                        default="MIXED",
                        max_length=20,
                        verbose_name="أسلوب التعلم",
                    ),
                ),
                (
                    "learning_pace",
                    models.CharField(
                        choices=[
                            ("SLOW", "بطيء"),
                            ("NORMAL", "عادي"),
                            ("FAST", "سريع"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="وتيرة التعلم",
                    ),
                ),
                (
                    "engagement_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نقاط التفاعل",
                    ),
                ),
                (
                    "attendance_pattern",
                    models.JSONField(default=dict, verbose_name="نمط الحضور"),
                ),
                (
                    "study_pattern",
                    models.JSONField(default=dict, verbose_name="نمط الدراسة"),
                ),
                (
                    "recommended_courses",
                    models.JSONField(default=list, verbose_name="المقررات المُوصى بها"),
                ),
                (
                    "recommended_study_plan",
                    models.JSONField(
                        default=dict, verbose_name="الخطة الدراسية المُوصى بها"
                    ),
                ),
                (
                    "improvement_suggestions",
                    models.JSONField(default=list, verbose_name="اقتراحات التحسين"),
                ),
                (
                    "stress_level",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="مستوى التوتر",
                    ),
                ),
                (
                    "motivation_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="مستوى الدافعية",
                    ),
                ),
                (
                    "satisfaction_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نقاط الرضا",
                    ),
                ),
                (
                    "technical_skills",
                    models.JSONField(default=dict, verbose_name="المهارات التقنية"),
                ),
                (
                    "soft_skills",
                    models.JSONField(default=dict, verbose_name="المهارات الناعمة"),
                ),
                (
                    "career_interests",
                    models.JSONField(default=list, verbose_name="الاهتمامات المهنية"),
                ),
                (
                    "intervention_alerts",
                    models.JSONField(default=list, verbose_name="تنبيهات التدخل"),
                ),
                (
                    "support_recommendations",
                    models.JSONField(default=list, verbose_name="توصيات الدعم"),
                ),
                (
                    "last_analysis_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر تحليل"
                    ),
                ),
                (
                    "analysis_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "يومي"),
                            ("WEEKLY", "أسبوعي"),
                            ("MONTHLY", "شهري"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                        verbose_name="تكرار التحليل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "الملف الذكي للطالب",
                "verbose_name_plural": "الملفات الذكية للطلاب",
                "ordering": ["user__first_name_ar"],
            },
        ),
        migrations.CreateModel(
            name="StudentPerformancePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "predicted_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="المعدل المتوقع",
                    ),
                ),
                (
                    "success_probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="احتمالية النجاح",
                    ),
                ),
                (
                    "dropout_risk",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="خطر التسرب",
                    ),
                ),
                (
                    "prediction_data",
                    models.JSONField(default=dict, verbose_name="بيانات التنبؤ"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="مستوى الثقة",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التنبؤ"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="صالح حتى"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبؤ أداء طالب",
                "verbose_name_plural": "تنبؤات أداء الطلاب",
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAIProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "teaching_effectiveness",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "ممتاز"),
                            ("VERY_GOOD", "جيد جداً"),
                            ("GOOD", "جيد"),
                            ("SATISFACTORY", "مرضي"),
                            ("NEEDS_IMPROVEMENT", "يحتاج تحسين"),
                        ],
                        default="SATISFACTORY",
                        max_length=20,
                        verbose_name="فعالية التدريس",
                    ),
                ),
                (
                    "student_satisfaction_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="متوسط رضا الطلاب",
                    ),
                ),
                (
                    "course_success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="معدل نجاح المقررات",
                    ),
                ),
                (
                    "teaching_style",
                    models.JSONField(default=dict, verbose_name="أسلوب التدريس"),
                ),
                (
                    "preferred_methods",
                    models.JSONField(default=list, verbose_name="الأساليب المفضلة"),
                ),
                (
                    "technology_adoption",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="تبني التكنولوجيا",
                    ),
                ),
                (
                    "workload_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="توازن العبء",
                    ),
                ),
                (
                    "research_activity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="النشاط البحثي",
                    ),
                ),
                (
                    "collaboration_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="مؤشر التعاون",
                    ),
                ),
                (
                    "development_areas",
                    models.JSONField(default=list, verbose_name="مجالات التطوير"),
                ),
                (
                    "recommended_training",
                    models.JSONField(default=list, verbose_name="التدريب المُوصى به"),
                ),
                (
                    "career_growth_path",
                    models.JSONField(default=dict, verbose_name="مسار النمو المهني"),
                ),
                (
                    "engagement_with_students",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="التفاعل مع الطلاب",
                    ),
                ),
                (
                    "innovation_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نقاط الابتكار",
                    ),
                ),
                (
                    "last_evaluation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر تقييم"
                    ),
                ),
                (
                    "evaluation_frequency",
                    models.CharField(
                        choices=[
                            ("SEMESTER", "فصلي"),
                            ("ANNUAL", "سنوي"),
                            ("BI_ANNUAL", "نصف سنوي"),
                        ],
                        default="SEMESTER",
                        max_length=20,
                        verbose_name="تكرار التقييم",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "الملف الذكي للأستاذ",
                "verbose_name_plural": "الملفات الذكية للأساتذة",
                "ordering": ["user__first_name_ar"],
            },
        ),
    ]
