# Generated by Django 5.2.7 on 2025-11-02 17:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ai', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('SUSPICIOUS_LOGIN', 'تسجيل دخول مشبوه'), ('UNUSUAL_BEHAVIOR', 'سلوك غير طبيعي'), ('DATA_BREACH_RISK', 'خطر تسريب بيانات'), ('SYSTEM_VULNERABILITY', 'ثغرة في النظام'), ('MALICIOUS_ACTIVITY', 'نشاط خبيث'), ('POLICY_VIOLATION', 'انتهاك سياسة'), ('PERFORMANCE_ANOMALY', 'شذوذ في الأداء')], max_length=25, verbose_name='نوع التنبيه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التنبيه')),
                ('description', models.TextField(verbose_name='وصف التنبيه')),
                ('system_component', models.CharField(blank=True, max_length=100, verbose_name='مكون النظام')),
                ('severity', models.CharField(choices=[('INFO', 'معلوماتي'), ('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='MEDIUM', max_length=10, verbose_name='مستوى الخطورة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('ACKNOWLEDGED', 'مُؤكد'), ('INVESTIGATING', 'قيد التحقيق'), ('RESOLVED', 'محلول'), ('FALSE_POSITIVE', 'إنذار كاذب')], default='ACTIVE', max_length=15, verbose_name='حالة التنبيه')),
                ('detection_data', models.JSONField(default=dict, verbose_name='بيانات الاكتشاف')),
                ('risk_indicators', models.JSONField(default=list, verbose_name='مؤشرات المخاطر')),
                ('confidence_level', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='مستوى الثقة')),
                ('recommended_actions', models.JSONField(default=list, verbose_name='الإجراءات الموصى بها')),
                ('automated_response', models.JSONField(default=dict, verbose_name='الاستجابة التلقائية')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts_affected', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المتأثر')),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='smart_ai.aimodel', verbose_name='النموذج المستخدم')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_alerts', to=settings.AUTH_USER_MODEL, verbose_name='مُعيّن إلى')),
            ],
            options={
                'verbose_name': 'تنبيه أمني ذكي',
                'verbose_name_plural': 'التنبيهات الأمنية الذكية',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='smart_ai_ai_alert_t_3dd1d1_idx'), models.Index(fields=['status', 'created_at'], name='smart_ai_ai_status_8d4832_idx'), models.Index(fields=['affected_user'], name='smart_ai_ai_affecte_333600_idx'), models.Index(fields=['confidence_level'], name='smart_ai_ai_confide_fc4f6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('COURSE_SELECTION', 'اختيار مقرر'), ('STUDY_PATH', 'مسار دراسي'), ('CAREER_GUIDANCE', 'توجيه مهني'), ('ACADEMIC_SUPPORT', 'دعم أكاديمي'), ('SKILL_DEVELOPMENT', 'تطوير مهارات'), ('TIME_MANAGEMENT', 'إدارة وقت'), ('RESOURCE_ALLOCATION', 'تخصيص موارد')], max_length=20, verbose_name='نوع التوصية')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التوصية')),
                ('description', models.TextField(verbose_name='وصف التوصية')),
                ('detailed_explanation', models.TextField(blank=True, verbose_name='الشرح المفصل')),
                ('recommendation_data', models.JSONField(default=dict, verbose_name='بيانات التوصية')),
                ('supporting_evidence', models.JSONField(default=list, verbose_name='الأدلة الداعمة')),
                ('expected_outcomes', models.JSONField(default=list, verbose_name='النتائج المتوقعة')),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='مستوى الثقة')),
                ('priority', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('IMPLEMENTED', 'مُنفذ'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=15, verbose_name='الحالة')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='صالح حتى')),
                ('implemented_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('user_feedback', models.TextField(blank=True, verbose_name='تعليق المستخدم')),
                ('feedback_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم التوصية')),
                ('effectiveness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نقاط الفعالية')),
                ('action_steps', models.JSONField(default=list, verbose_name='خطوات العمل')),
                ('required_resources', models.JSONField(default=list, verbose_name='الموارد المطلوبة')),
                ('estimated_completion_time', models.CharField(blank=True, max_length=50, verbose_name='الوقت المتوقع للإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_recommendations', to='smart_ai.aimodel', verbose_name='النموذج المستخدم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_smart_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='أُنشأ بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توصية ذكية',
                'verbose_name_plural': 'التوصيات الذكية',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='smart_ai_sm_user_id_512752_idx'), models.Index(fields=['recommendation_type', 'priority'], name='smart_ai_sm_recomme_6d4c9a_idx'), models.Index(fields=['valid_until'], name='smart_ai_sm_valid_u_bccb4a_idx'), models.Index(fields=['confidence_score'], name='smart_ai_sm_confide_b1c7d2_idx')],
            },
        ),
    ]
