# Generated by Django 4.2.16 on 2025-10-21 19:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "مدير النظام الرئيسي"),
                            ("ADMIN", "مدير النظام"),
                            ("DEAN", "عميد الكلية"),
                            ("HEAD_OF_DEPARTMENT", "رئيس القسم"),
                            ("TEACHER", "أستاذ"),
                            ("ASSISTANT_TEACHER", "مساعد تدريس"),
                            ("STUDENT", "طالب"),
                            ("ACCOUNTANT", "محاسب"),
                            ("HR_MANAGER", "مدير الموارد البشرية"),
                            ("REGISTRAR", "مسجل أكاديمي"),
                            ("LIBRARIAN", "أمين المكتبة"),
                            ("IT_SUPPORT", "دعم تقني"),
                            ("SECURITY_OFFICER", "ضابط أمن"),
                            ("GUEST", "زائر"),
                        ],
                        default="STUDENT",
                        max_length=20,
                        verbose_name="الدور الوظيفي",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="رقم الموظف",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="رقم الطالب",
                    ),
                ),
                (
                    "first_name_ar",
                    models.CharField(max_length=50, verbose_name="الاسم الأول - عربي"),
                ),
                (
                    "last_name_ar",
                    models.CharField(max_length=50, verbose_name="اسم العائلة - عربي"),
                ),
                (
                    "first_name_en",
                    models.CharField(
                        max_length=50, verbose_name="الاسم الأول - إنجليزي"
                    ),
                ),
                (
                    "last_name_en",
                    models.CharField(
                        max_length=50, verbose_name="اسم العائلة - إنجليزي"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الاسم الأوسط"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "ذكر"), ("F", "أنثى")],
                        max_length=1,
                        verbose_name="الجنس",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "place_of_birth",
                    models.CharField(max_length=100, verbose_name="مكان الميلاد"),
                ),
                (
                    "nationality",
                    models.CharField(max_length=50, verbose_name="الجنسية"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهاتف يجب أن يكون بالصيغة: '+966501234567'. الحد الأقصى 15 رقم.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "phone_number_2",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهاتف يجب أن يكون بالصيغة: '+966501234567'. الحد الأقصى 15 رقم.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم هاتف إضافي",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        max_length=255, verbose_name="العنوان - السطر الأول"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="العنوان - السطر الثاني",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="المنطقة/المحافظة"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="الرمز البريدي"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="السعودية", max_length=100, verbose_name="البلد"
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "expected_graduation",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التخرج المتوقع"
                    ),
                ),
                (
                    "academic_level",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="المستوى الأكاديمي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("SUSPENDED", "موقوف"),
                            ("GRADUATED", "متخرج"),
                            ("TRANSFERRED", "محول"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="مُوثق"),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رمز التوثيق"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0, verbose_name="محاولات تسجيل دخول فاشلة"
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مُغلق حتى"
                    ),
                ),
                (
                    "privacy_settings",
                    models.JSONField(default=dict, verbose_name="إعدادات الخصوصية"),
                ),
                (
                    "notification_preferences",
                    models.JSONField(default=dict, verbose_name="تفضيلات الإشعارات"),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")],
                        default="ar",
                        max_length=5,
                        verbose_name="لغة الواجهة",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="اسم جهة الاتصال للطوارئ",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهاتف يجب أن يكون بالصيغة: '+966501234567'. الحد الأقصى 15 رقم.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="هاتف جهة الاتصال للطوارئ",
                    ),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="صلة القرابة لجهة الاتصال",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشأ بواسطة",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "ordering": ["first_name_ar", "last_name_ar"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "فاتح"),
                            ("dark", "داكن"),
                            ("auto", "تلقائي"),
                        ],
                        default="light",
                        max_length=10,
                        verbose_name="المظهر",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")],
                        default="ar",
                        max_length=5,
                        verbose_name="اللغة",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Riyadh",
                        max_length=50,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="إشعارات البريد الإلكتروني"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="إشعارات الرسائل النصية"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(default=True, verbose_name="إشعارات فورية"),
                ),
                (
                    "dashboard_layout",
                    models.JSONField(default=dict, verbose_name="تخطيط لوحة التحكم"),
                ),
                (
                    "favorite_widgets",
                    models.JSONField(default=list, verbose_name="الأدوات المفضلة"),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[("public", "عام"), ("private", "خاص")],
                        default="private",
                        max_length=10,
                        verbose_name="مستوى الخصوصية",
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(default=True, verbose_name="إظهار الحالة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تفضيلات المستخدم",
                "verbose_name_plural": "تفضيلات المستخدمين",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "تسجيل دخول"),
                            ("LOGOUT", "تسجيل خروج"),
                            ("VIEW", "عرض"),
                            ("CREATE", "إنشاء"),
                            ("UPDATE", "تحديث"),
                            ("DELETE", "حذف"),
                            ("DOWNLOAD", "تحميل"),
                            ("UPLOAD", "رفع ملف"),
                            ("EXPORT", "تصدير"),
                            ("PRINT", "طباعة"),
                        ],
                        max_length=10,
                        verbose_name="الإجراء",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="الوصف")),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(verbose_name="متصفح المستخدم")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشاط المستخدم",
                "verbose_name_plural": "نشاطات المستخدمين",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="students_us_user_id_27674d_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="students_us_action_4d84e5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="teacher_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الأستاذ",
                    ),
                ),
                (
                    "employee_id_display",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الموظف"
                    ),
                ),
                (
                    "academic_rank",
                    models.CharField(
                        choices=[
                            ("PROFESSOR", "أستاذ"),
                            ("ASSOCIATE_PROFESSOR", "أستاذ مشارك"),
                            ("ASSISTANT_PROFESSOR", "أستاذ مساعد"),
                            ("LECTURER", "محاضر"),
                            ("TEACHING_ASSISTANT", "معيد"),
                            ("INSTRUCTOR", "مدرس"),
                        ],
                        max_length=25,
                        verbose_name="الرتبة الأكاديمية",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "دوام كامل"),
                            ("PART_TIME", "دوام جزئي"),
                            ("VISITING", "أستاذ زائر"),
                            ("ADJUNCT", "مساعد تدريس"),
                            ("EMERITUS", "أستاذ متقاعد"),
                        ],
                        default="FULL_TIME",
                        max_length=15,
                        verbose_name="نوع التوظيف",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="تاريخ التوظيف")),
                (
                    "tenure_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الحصول على الثبات"
                    ),
                ),
                (
                    "highest_degree",
                    models.CharField(max_length=50, verbose_name="أعلى مؤهل علمي"),
                ),
                (
                    "degree_institution",
                    models.CharField(max_length=200, verbose_name="مؤسسة المؤهل"),
                ),
                (
                    "degree_year",
                    models.IntegerField(verbose_name="سنة الحصول على المؤهل"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=200, verbose_name="التخصص الدقيق"),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم المكتب"
                    ),
                ),
                (
                    "office_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف المكتب"
                    ),
                ),
                (
                    "office_hours",
                    models.TextField(blank=True, verbose_name="ساعات المكتب"),
                ),
                (
                    "total_courses_taught",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي المقررات المُدرسة"
                    ),
                ),
                (
                    "current_teaching_load",
                    models.IntegerField(
                        default=0, verbose_name="العبء التدريسي الحالي"
                    ),
                ),
                (
                    "max_teaching_load",
                    models.IntegerField(
                        default=12, verbose_name="الحد الأقصى للعبء التدريسي"
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(blank=True, verbose_name="الاهتمامات البحثية"),
                ),
                (
                    "publications_count",
                    models.IntegerField(
                        default=0, verbose_name="عدد المنشورات العلمية"
                    ),
                ),
                (
                    "research_projects",
                    models.TextField(blank=True, verbose_name="المشاريع البحثية"),
                ),
                (
                    "teaching_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم التدريس",
                    ),
                ),
                (
                    "awards",
                    models.TextField(blank=True, verbose_name="الجوائز والتكريمات"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, verbose_name="السيرة الذاتية المختصرة"
                    ),
                ),
                (
                    "languages_spoken",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اللغات المتقنة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "can_supervise_thesis",
                    models.BooleanField(
                        default=False, verbose_name="يمكنه الإشراف على الرسائل"
                    ),
                ),
                (
                    "max_thesis_supervision",
                    models.IntegerField(default=5, verbose_name="الحد الأقصى للإشراف"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.college",
                        verbose_name="الكلية",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف أكاديمي - أستاذ",
                "verbose_name_plural": "الملفات الأكاديمية - الأساتذة",
                "ordering": ["academic_rank", "user__first_name_ar"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "student_id_display",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="رقم الطالب"
                    ),
                ),
                (
                    "study_status",
                    models.CharField(
                        choices=[
                            ("REGULAR", "نظامي"),
                            ("PART_TIME", "جزئي"),
                            ("DISTANCE", "تعليم عن بُعد"),
                            ("EXCHANGE", "طالب تبادل"),
                        ],
                        default="REGULAR",
                        max_length=15,
                        verbose_name="نوع الدراسة",
                    ),
                ),
                (
                    "academic_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="المستوى الأكاديمي",
                    ),
                ),
                (
                    "current_semester",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="الفصل الدراسي الحالي",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="السنة الأكاديمية"),
                ),
                (
                    "cumulative_gpa",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="المعدل التراكمي",
                    ),
                ),
                (
                    "semester_gpa",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="معدل الفصل",
                    ),
                ),
                (
                    "total_credit_hours",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي الساعات المكتسبة"
                    ),
                ),
                (
                    "completed_credit_hours",
                    models.IntegerField(default=0, verbose_name="الساعات المكتملة"),
                ),
                (
                    "required_credit_hours",
                    models.IntegerField(
                        default=132, verbose_name="الساعات المطلوبة للتخرج"
                    ),
                ),
                (
                    "academic_standing",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "ممتاز"),
                            ("VERY_GOOD", "جيد جداً"),
                            ("GOOD", "جيد"),
                            ("SATISFACTORY", "مقبول"),
                            ("PROBATION", "تحت المراقبة"),
                            ("ACADEMIC_WARNING", "إنذار أكاديمي"),
                        ],
                        default="SATISFACTORY",
                        max_length=20,
                        verbose_name="المستوى الأكاديمي",
                    ),
                ),
                (
                    "warnings_count",
                    models.IntegerField(default=0, verbose_name="عدد الإنذارات"),
                ),
                (
                    "is_on_probation",
                    models.BooleanField(default=False, verbose_name="تحت المراقبة"),
                ),
                (
                    "probation_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ بداية المراقبة"
                    ),
                ),
                (
                    "expected_graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التخرج المتوقع"
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التخرج الفعلي"
                    ),
                ),
                (
                    "is_graduated",
                    models.BooleanField(default=False, verbose_name="متخرج"),
                ),
                (
                    "graduation_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="معدل التخرج",
                    ),
                ),
                (
                    "graduation_honors",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="مراتب الشرف"
                    ),
                ),
                (
                    "advisor_assignment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ تعيين المستشار"
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, verbose_name="احتياجات خاصة"),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="حالات طبية"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات إضافية")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "academic_advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advised_students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستشار الأكاديمي",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.college",
                        verbose_name="الكلية",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.major",
                        verbose_name="التخصص",
                    ),
                ),
                (
                    "minor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minor_students",
                        to="courses.major",
                        verbose_name="التخصص الفرعي",
                    ),
                ),
            ],
            options={
                "verbose_name": "الملف الأكاديمي للطالب",
                "verbose_name_plural": "الملفات الأكاديمية للطلاب",
                "ordering": ["student_id_display"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "status"], name="students_us_role_d852e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["student_id"], name="students_us_student_749420_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["employee_id"], name="students_us_employe_db4e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="students_us_email_1cf261_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["college", "department"], name="students_te_college_921a50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["academic_rank"], name="students_te_academi_b7cc40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["employment_type"], name="students_te_employm_2e3313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["college", "department", "major"],
                name="students_st_college_641f06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["academic_level", "current_semester"],
                name="students_st_academi_d08bee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["cumulative_gpa"], name="students_st_cumulat_13ea5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["academic_standing"], name="students_st_academi_320b95_idx"
            ),
        ),
    ]
