# Generated by Django 4.2.16 on 2025-10-22 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="العنوان - السطر الأول"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="المدينة"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name_ar",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="الاسم الأول - عربي"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="الاسم الأول - إنجليزي"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "ذكر"), ("F", "أنثى")],
                max_length=1,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name_ar",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="اسم العائلة - عربي"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="اسم العائلة - إنجليزي"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, verbose_name="الجنسية"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يكون بالصيغة: '+966501234567'. الحد الأقصى 15 رقم.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="مكان الميلاد"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state_province",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="المنطقة/المحافظة"
            ),
        ),
    ]
