# Generated by Django 5.2.7 on 2025-11-02 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID', 'بطاقة هوية'), ('PASSPORT', 'جواز سفر'), ('BIRTH_CERT', 'شهادة ميلاد'), ('ACADEMIC_CERT', 'شهادة أكاديمية'), ('MEDICAL_REPORT', 'تقرير طبي'), ('FINANCIAL_DOC', 'وثيقة مالية'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوثيقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/', verbose_name='الملف')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم الملف')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوثيق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='تم التوثيق بواسطة')),
            ],
            options={
                'verbose_name': 'وثيقة طالب',
                'verbose_name_plural': 'وثائق الطلاب',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='students_st_student_7712b0_idx'), models.Index(fields=['is_verified'], name='students_st_is_veri_555fc0_idx'), models.Index(fields=['uploaded_at'], name='students_st_uploade_7f7595_idx')],
            },
        ),
    ]
