# Generated by Django 4.2.16 on 2025-10-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_user_address_line_1_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
    ]
