# Generated by Django 4.2.16 on 2025-10-29 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATE", "User Created"),
                            ("USER_DELETE", "User Deleted"),
                            ("USER_ROLE_CHANGE", "User Role Changed"),
                            ("SYSTEM_CONFIG", "System Configuration Changed"),
                            ("BACKUP_RESTORE", "Backup/Restore Operation"),
                            ("MAINTENANCE_MODE", "Maintenance Mode Toggle"),
                            ("BULK_OPERATION", "Bulk Operation"),
                            ("DATA_EXPORT", "Data Export"),
                            ("DATA_IMPORT", "Data Import"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("after_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminDashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("CHART", "Chart"),
                            ("STAT", "Statistics"),
                            ("TABLE", "Data Table"),
                            ("CALENDAR", "Calendar"),
                            ("ACTIVITY", "Activity Feed"),
                            ("ALERT", "Alert List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(default=dict)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                (
                    "width",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_permission", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_dashboard_widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("FULL", "Full"), ("PARTIAL", "Partial")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "backup_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        default="System Under Maintenance", max_length=200
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="We are currently performing system maintenance. Please try again later."
                    ),
                ),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "allowed_ips",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of IP addresses allowed during maintenance",
                    ),
                ),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "maintenance_mode",
            },
        ),
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("SECURITY", "Security"),
                            ("MAINTENANCE", "Maintenance"),
                            ("ACADEMIC", "Academic"),
                            ("FINANCIAL", "Financial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("auto_dismiss_after", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_configurations",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("category", models.CharField(default="performance", max_length=50)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_metrics",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
