# Generated by Django 4.2.16 on 2025-10-29 19:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="السنة الأكاديمية"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="السنة الحالية"),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="الميزانية الإجمالية",
                    ),
                ),
                (
                    "allocated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="الميزانية المخصصة",
                    ),
                ),
                (
                    "spent_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="الميزانية المُنفقة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سنة أكاديمية مالية",
                "verbose_name_plural": "السنوات الأكاديمية المالية",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=200, verbose_name="اسم هيكل الرسوم - عربي"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم هيكل الرسوم - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز الهيكل"
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("UNDERGRADUATE", "بكالوريوس"),
                            ("GRADUATE", "دراسات عليا"),
                            ("DIPLOMA", "دبلوم"),
                            ("CERTIFICATE", "شهادة"),
                        ],
                        max_length=20,
                        verbose_name="نوع البرنامج",
                    ),
                ),
                (
                    "student_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "نظامي"),
                            ("PART_TIME", "جزئي"),
                            ("DISTANCE", "تعليم عن بُعد"),
                            ("INTERNATIONAL", "دولي"),
                        ],
                        default="REGULAR",
                        max_length=15,
                        verbose_name="نوع الطالب",
                    ),
                ),
                (
                    "tuition_fee_per_credit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="رسوم الساعة المعتمدة",
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="رسوم التسجيل",
                    ),
                ),
                (
                    "activity_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="رسوم الأنشطة",
                    ),
                ),
                (
                    "lab_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="رسوم المختبرات",
                    ),
                ),
                (
                    "library_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="رسوم المكتبة",
                    ),
                ),
                (
                    "medical_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="رسوم طبية",
                    ),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="رسوم تأمين",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="سارية من")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="سارية حتى"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "هيكل رسوم",
                "verbose_name_plural": "هياكل الرسوم",
                "ordering": ["program_type", "student_type", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الرسوم - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم الرسوم - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز الرسوم"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TUITION", "رسوم دراسية"),
                            ("APPLICATION", "رسوم تقديم"),
                            ("REGISTRATION", "رسوم تسجيل"),
                            ("LATE_REGISTRATION", "رسوم تسجيل متأخر"),
                            ("LABORATORY", "رسوم معامل"),
                            ("LIBRARY", "رسوم مكتبة"),
                            ("ACTIVITY", "رسوم أنشطة"),
                            ("GRADUATION", "رسوم تخرج"),
                            ("TRANSCRIPT", "رسوم كشف درجات"),
                            ("CERTIFICATE", "رسوم شهادات"),
                            ("PARKING", "رسوم مواقف"),
                            ("HOUSING", "رسوم سكن"),
                            ("MEALS", "رسوم وجبات"),
                            ("MEDICAL", "رسوم طبية"),
                            ("INSURANCE", "رسوم تأمين"),
                            ("OTHER", "رسوم أخرى"),
                        ],
                        max_length=20,
                        verbose_name="فئة الرسوم",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("FIXED", "مبلغ ثابت"),
                            ("PER_CREDIT", "لكل ساعة معتمدة"),
                            ("PERCENTAGE", "نسبة مئوية"),
                            ("VARIABLE", "متغير"),
                        ],
                        default="FIXED",
                        max_length=15,
                        verbose_name="طريقة الحساب",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="المبلغ الأساسي",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="إلزامي"),
                ),
                (
                    "is_refundable",
                    models.BooleanField(default=False, verbose_name="قابل للاسترداد"),
                ),
                (
                    "payment_deadline_days",
                    models.IntegerField(default=30, verbose_name="مهلة السداد (أيام)"),
                ),
                (
                    "applies_to_new_students",
                    models.BooleanField(default=True, verbose_name="للطلاب الجدد"),
                ),
                (
                    "applies_to_continuing_students",
                    models.BooleanField(default=True, verbose_name="للطلاب المستمرين"),
                ),
                (
                    "applies_to_graduate_students",
                    models.BooleanField(
                        default=True, verbose_name="لطلاب الدراسات العليا"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="ساري من"
                    ),
                ),
                (
                    "effective_until",
                    models.DateField(blank=True, null=True, verbose_name="ساري حتى"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الرسوم"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نوع رسوم",
                "verbose_name_plural": "أنواع الرسوم",
                "ordering": ["category", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_name",
                    models.CharField(max_length=200, verbose_name="اسم التقرير"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "تقرير يومي"),
                            ("WEEKLY", "تقرير أسبوعي"),
                            ("MONTHLY", "تقرير شهري"),
                            ("QUARTERLY", "تقرير ربع سنوي"),
                            ("ANNUAL", "تقرير سنوي"),
                            ("CUSTOM", "تقرير مخصص"),
                        ],
                        max_length=15,
                        verbose_name="نوع التقرير",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="إجمالي الإيرادات",
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="إجمالي المصروفات",
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="صافي الدخل",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(default=dict, verbose_name="بيانات التقرير"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "قيد الإنتاج"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "فاشل"),
                        ],
                        default="GENERATING",
                        max_length=15,
                        verbose_name="حالة التقرير",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الملف"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإنتاج"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تقرير مالي",
                "verbose_name_plural": "التقارير المالية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الدفعة"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "نقداً"),
                            ("CREDIT_CARD", "بطاقة ائتمان"),
                            ("DEBIT_CARD", "بطاقة خصم"),
                            ("BANK_TRANSFER", "تحويل بنكي"),
                            ("ONLINE_PAYMENT", "دفع إلكتروني"),
                            ("CHECK", "شيك"),
                            ("SCHOLARSHIP", "منحة دراسية"),
                            ("FINANCIAL_AID", "مساعدة مالية"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المعالجة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("PROCESSING", "قيد المعالجة"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "فاشل"),
                            ("CANCELLED", "ملغي"),
                            ("REFUNDED", "مُسترد"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="معرف المعاملة"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم البنك"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الشيك"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الدفعة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "المدفوعات",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ المخصص"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "توزيع دفعة",
                "verbose_name_plural": "توزيعات الدفعات",
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم المنحة - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم المنحة - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز المنحة"
                    ),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("FULL_TUITION", "منحة كاملة للرسوم الدراسية"),
                            ("PARTIAL_TUITION", "منحة جزئية للرسوم الدراسية"),
                            ("NEED_BASED", "منحة على أساس الحاجة"),
                            ("MERIT_BASED", "منحة على أساس الجدارة"),
                            ("ATHLETIC", "منحة رياضية"),
                            ("ACADEMIC_EXCELLENCE", "منحة التفوق الأكاديمي"),
                            ("RESEARCH", "منحة بحثية"),
                            ("INTERNATIONAL", "منحة دولية"),
                            ("EMPLOYEE_DEPENDENT", "منحة أبناء الموظفين"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع المنحة",
                    ),
                ),
                (
                    "funding_source",
                    models.CharField(
                        choices=[
                            ("UNIVERSITY", "الجامعة"),
                            ("GOVERNMENT", "حكومية"),
                            ("PRIVATE_DONOR", "متبرع خاص"),
                            ("FOUNDATION", "مؤسسة"),
                            ("CORPORATE", "شركة"),
                            ("INTERNATIONAL", "دولية"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="مصدر التمويل",
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الميزانية الإجمالية",
                    ),
                ),
                (
                    "allocated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="الميزانية المخصصة",
                    ),
                ),
                (
                    "min_gpa",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="الحد الأدنى للمعدل",
                    ),
                ),
                (
                    "max_family_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="الحد الأقصى لدخل الأسرة",
                    ),
                ),
                (
                    "requires_financial_need",
                    models.BooleanField(default=False, verbose_name="يتطلب حاجة مالية"),
                ),
                (
                    "requires_community_service",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب خدمة مجتمعية"
                    ),
                ),
                (
                    "renewable",
                    models.BooleanField(default=True, verbose_name="قابلة للتجديد"),
                ),
                (
                    "application_start_date",
                    models.DateField(verbose_name="تاريخ بداية التقديم"),
                ),
                (
                    "application_end_date",
                    models.DateField(verbose_name="تاريخ نهاية التقديم"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشطة"),
                            ("SUSPENDED", "موقوفة"),
                            ("TERMINATED", "منتهية"),
                            ("COMPLETED", "مكتملة"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="حالة المنحة",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف المنحة")),
                ("requirements", models.TextField(verbose_name="المتطلبات")),
                ("benefits", models.TextField(verbose_name="المزايا")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="جهة الاتصال"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد جهة الاتصال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "منحة دراسية",
                "verbose_name_plural": "المنح الدراسية",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الطلب"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التقديم"
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "مقدم"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("APPROVED", "موافق عليه"),
                            ("REJECTED", "مرفوض"),
                            ("WAITLISTED", "في قائمة الانتظار"),
                            ("WITHDRAWN", "منسحب"),
                        ],
                        default="SUBMITTED",
                        max_length=15,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "family_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="دخل الأسرة",
                    ),
                ),
                (
                    "current_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="المعدل الحالي",
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ المطلوب"
                    ),
                ),
                (
                    "awarded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="المبلغ الممنوح",
                    ),
                ),
                (
                    "documents_uploaded",
                    models.JSONField(default=list, verbose_name="المستندات المرفوعة"),
                ),
                (
                    "reviewer_comments",
                    models.TextField(blank=True, verbose_name="تعليقات المراجع"),
                ),
                (
                    "decision_reason",
                    models.TextField(blank=True, verbose_name="سبب القرار"),
                ),
                ("essay", models.TextField(blank=True, verbose_name="مقال الطالب")),
                (
                    "extracurricular_activities",
                    models.TextField(blank=True, verbose_name="الأنشطة اللامنهجية"),
                ),
                (
                    "community_service_hours",
                    models.IntegerField(
                        default=0, verbose_name="ساعات الخدمة المجتمعية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "طلب منحة دراسية",
                "verbose_name_plural": "طلبات المنح الدراسية",
                "ordering": ["-submitted_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الحساب"
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("SUSPENDED", "موقوف"),
                            ("CLOSED", "مُغلق"),
                            ("HOLD", "محجوز"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="حالة الحساب",
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="إجمالي المستحقات",
                    ),
                ),
                (
                    "total_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="إجمالي المدفوعات",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                (
                    "total_scholarships",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="إجمالي المنح",
                    ),
                ),
                (
                    "total_financial_aid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="إجمالي المساعدات المالية",
                    ),
                ),
                (
                    "total_discounts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="إجمالي الخصومات",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="الحد الائتماني",
                    ),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "جيد"),
                            ("WARNING", "تحذير"),
                            ("POOR", "ضعيف"),
                            ("BLOCKED", "محظور"),
                        ],
                        default="GOOD",
                        max_length=15,
                        verbose_name="الحالة الائتمانية",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر دفعة"
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق التالي"
                    ),
                ),
                (
                    "auto_pay_enabled",
                    models.BooleanField(
                        default=False, verbose_name="الدفع التلقائي مُفعل"
                    ),
                ),
                (
                    "payment_reminders_enabled",
                    models.BooleanField(
                        default=True, verbose_name="تذكيرات الدفع مُفعلة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "حساب مالي للطالب",
                "verbose_name_plural": "الحسابات المالية للطلاب",
                "ordering": ["student__first_name_ar"],
            },
        ),
        migrations.CreateModel(
            name="StudentCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الأصلي"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="مبلغ الخصم",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ النهائي"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "charge_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المستحق"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "semester",
                    models.CharField(max_length=20, verbose_name="الفصل الدراسي"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("POSTED", "مُرحل"),
                            ("PAID", "مدفوع"),
                            ("PARTIALLY_PAID", "مدفوع جزئياً"),
                            ("CANCELLED", "ملغي"),
                            ("REFUNDED", "مُسترد"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المستحق"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الترحيل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "مستحق طالب",
                "verbose_name_plural": "مستحقات الطلاب",
                "ordering": ["-charge_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="السنة الأكاديمية"),
                ),
                (
                    "semester",
                    models.CharField(max_length=20, verbose_name="الفصل الدراسي"),
                ),
                (
                    "total_credit_hours",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي الساعات المعتمدة"
                    ),
                ),
                (
                    "tuition_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="مبلغ الرسوم الدراسية",
                    ),
                ),
                (
                    "additional_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="الرسوم الإضافية",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="إجمالي المبلغ"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="مبلغ الخصم",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "payment_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="آخر موعد للدفع"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "معلق"),
                            ("PARTIAL", "دُفع جزئياً"),
                            ("PAID", "مدفوع"),
                            ("OVERDUE", "متأخر"),
                            ("WAIVED", "معفى"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="حالة الدفع",
                    ),
                ),
                (
                    "is_installment_allowed",
                    models.BooleanField(default=True, verbose_name="السماح بالتقسيط"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "رسوم طالب",
                "verbose_name_plural": "رسوم الطلاب",
                "ordering": ["-academic_year", "semester", "student__first_name"],
            },
        ),
    ]
