# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfee",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_student_fees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_fees",
                to="finance.feestructure",
                verbose_name="هيكل الرسوم",
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.academicyear",
                verbose_name="السنة الأكاديمية",
            ),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="course_offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.courseoffering",
                verbose_name="عرض المقرر",
            ),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="fee_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.feetype",
                verbose_name="نوع الرسوم",
            ),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_charges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رُحل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="student_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="finance.studentaccount",
                verbose_name="حساب الطالب",
            ),
        ),
        migrations.AddField(
            model_name="studentaccount",
            name="current_academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.academicyear",
                verbose_name="السنة الأكاديمية الحالية",
            ),
        ),
        migrations.AddField(
            model_name="studentaccount",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_account",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_scholarship_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipapplication",
            name="scholarship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="finance.scholarship",
                verbose_name="المنحة",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipapplication",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarship_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.academicyear",
                verbose_name="السنة الأكاديمية",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_scholarships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="finance.studentcharge",
                verbose_name="المستحق",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="finance.payment",
                verbose_name="الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.academicyear",
                verbose_name="السنة الأكاديمية",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وافق عليه",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عولج بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.studentaccount",
                verbose_name="حساب الطالب",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.academicyear",
                verbose_name="السنة الأكاديمية",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_financial_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنتج بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="feetype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_fee_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_fee_structures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["student", "status"], name="finance_stu_student_7c0999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["academic_year", "semester"],
                name="finance_stu_academi_09a2fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["due_date"], name="finance_stu_due_dat_e9a046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(fields=["status"], name="finance_stu_status_324f93_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentfee",
            unique_together={("student", "academic_year", "semester")},
        ),
        migrations.AddIndex(
            model_name="studentcharge",
            index=models.Index(
                fields=["student_account", "status"],
                name="finance_stu_student_5f9950_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentcharge",
            index=models.Index(
                fields=["due_date"], name="finance_stu_due_dat_c35f08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentcharge",
            index=models.Index(
                fields=["academic_year", "semester"],
                name="finance_stu_academi_f52c28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentcharge",
            index=models.Index(
                fields=["reference_number"], name="finance_stu_referen_c7d4fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentaccount",
            index=models.Index(
                fields=["account_number"], name="finance_stu_account_7eb388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentaccount",
            index=models.Index(
                fields=["account_status"], name="finance_stu_account_bddb2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentaccount",
            index=models.Index(
                fields=["current_balance"], name="finance_stu_current_8dbd0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipapplication",
            index=models.Index(fields=["status"], name="finance_sch_status_1dc41e_idx"),
        ),
        migrations.AddIndex(
            model_name="scholarshipapplication",
            index=models.Index(
                fields=["submitted_date"], name="finance_sch_submitt_c230cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipapplication",
            index=models.Index(
                fields=["application_number"], name="finance_sch_applica_c8b616_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scholarshipapplication",
            unique_together={("student", "scholarship")},
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(
                fields=["scholarship_type", "status"],
                name="finance_sch_scholar_2e2f44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(
                fields=["academic_year"], name="finance_sch_academi_ae85db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(fields=["code"], name="finance_sch_code_05e3b1_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["payment"], name="finance_pay_payment_c4ed6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["charge"], name="finance_pay_charge__e72191_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentallocation",
            unique_together={("payment", "charge")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student_account", "status"],
                name="finance_pay_student_c5aec3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="finance_pay_payment_72f761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_number"], name="finance_pay_payment_bb9d71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="finance_pay_transac_c95172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(
                fields=["report_type", "academic_year"],
                name="finance_fin_report__dbae6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(
                fields=["start_date", "end_date"], name="finance_fin_start_d_21c54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(fields=["status"], name="finance_fin_status_545792_idx"),
        ),
        migrations.AddIndex(
            model_name="feetype",
            index=models.Index(
                fields=["category", "is_active"], name="finance_fee_categor_133ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feetype",
            index=models.Index(fields=["code"], name="finance_fee_code_f20f36_idx"),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["program_type", "student_type", "is_active"],
                name="finance_fee_program_9482b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="finance_fee_effecti_a604cf_idx",
            ),
        ),
    ]
