# Generated by Django 4.2.7 on 2025-10-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_recommendations',
                'ordering': ['-recommendation_score'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.CharField(max_length=2)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factors', models.JSONField(help_text='Factors influencing the prediction')),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'performance_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period_start', models.DateField()),
                ('analysis_period_end', models.DateField()),
                ('pattern_data', models.JSONField(help_text='Analyzed study pattern data')),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('improvement_suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_patterns',
                'ordering': ['-created_at'],
            },
        ),
    ]
