# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TEACHER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="academic.semester",
            ),
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_prerequisites",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="prerequisite_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_prerequisite_for",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="academic.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academic.semester",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academic.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicprogram",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_programs",
                to="courses.department",
            ),
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.semester",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="prerequisite",
            unique_together={("course", "prerequisite_course")},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("enrollment", "date")},
        ),
    ]
