# Generated by Django 4.2.7 on 2025-10-16 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'All Students'), ('TEACHERS', 'All Teachers'), ('STAFF', 'All Staff'), ('SPECIFIC_ROLES', 'Specific Roles'), ('SPECIFIC_USERS', 'Specific Users'), ('DEPARTMENT', 'Department'), ('PROGRAM', 'Academic Program')], default='ALL', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('NORMAL', 'Normal Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ALERT', 'Alert'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App Notification'), ('PUSH', 'Push Notification')], default='IN_APP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=10)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_enrollment', models.BooleanField(default=True)),
                ('email_grades', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_urgent_only', models.BooleanField(default=True)),
                ('sms_payments', models.BooleanField(default=True)),
                ('sms_reminders', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_sound', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_grades', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('ENROLLMENT_CONFIRMATION', 'Enrollment Confirmation'), ('GRADE_POSTED', 'Grade Posted'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder'), ('PAYMENT_DUE', 'Payment Due Notice'), ('PAYMENT_RECEIVED', 'Payment Received Confirmation'), ('ATTENDANCE_WARNING', 'Attendance Warning'), ('SEMESTER_START', 'Semester Start Notice'), ('REGISTRATION_OPEN', 'Registration Open'), ('ACADEMIC_WARNING', 'Academic Warning'), ('GRADUATION_REMINDER', 'Graduation Reminder'), ('GENERAL_ANNOUNCEMENT', 'General Announcement')], max_length=30, unique=True)),
                ('subject_template', models.CharField(max_length=200)),
                ('email_template', models.TextField()),
                ('sms_template', models.TextField(blank=True, help_text='Keep under 160 characters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
