# Generated by Django 4.2.7 on 2025-10-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrolled', models.IntegerField(default=0)),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dropout_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('student_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('total_students', models.IntegerField(default=0)),
                ('new_enrollments', models.IntegerField(default=0)),
                ('graduated_students', models.IntegerField(default=0)),
                ('dropped_students', models.IntegerField(default=0)),
                ('average_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrollment_statistics',
                'ordering': ['-academic_year', '-semester'],
            },
        ),
        migrations.CreateModel(
            name='StudentPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_credits', models.IntegerField()),
                ('credits_earned', models.IntegerField()),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_performance_reports',
                'ordering': ['-academic_year', '-semester'],
            },
        ),
    ]
