# Generated by Django 4.2.16 on 2025-10-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_alter_course_prerequisites_classroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0003_alter_useractivity_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.IntegerField()),
                ("semester", models.IntegerField()),
                ("total_students", models.IntegerField(default=0)),
                ("new_enrollments", models.IntegerField(default=0)),
                ("graduated_students", models.IntegerField(default=0)),
                ("dropped_students", models.IntegerField(default=0)),
                (
                    "average_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enrollment_statistics",
                "ordering": ["-academic_year", "-semester"],
                "unique_together": {("academic_year", "semester")},
            },
        ),
        migrations.CreateModel(
            name="CourseAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_enrolled", models.IntegerField(default=0)),
                (
                    "average_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "pass_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dropout_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "student_satisfaction_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_offering",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="courses.courseoffering",
                    ),
                ),
            ],
            options={
                "db_table": "course_analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.IntegerField()),
                ("semester", models.IntegerField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("total_credits", models.IntegerField()),
                ("credits_earned", models.IntegerField()),
                ("rank_in_class", models.IntegerField(blank=True, null=True)),
                ("total_students", models.IntegerField(blank=True, null=True)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "student_performance_reports",
                "ordering": ["-academic_year", "-semester"],
                "unique_together": {("student", "academic_year", "semester")},
            },
        ),
    ]
