# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("courses", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentperformancereport",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentperformancereport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_reports",
                to="students.studentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentstatistics",
            unique_together={("academic_year", "semester")},
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="course_offering",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="courses.courseoffering",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentperformancereport",
            unique_together={("student", "academic_year", "semester")},
        ),
    ]
