# Generated by Django 4.2.16 on 2025-10-29 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="السنة الأكاديمية"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="السنة الحالية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سنة أكاديمية",
                "verbose_name_plural": "السنوات الأكاديمية",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان التكليف"),
                ),
                ("description", models.TextField(verbose_name="وصف التكليف")),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("HOMEWORK", "واجب منزلي"),
                            ("PROJECT", "مشروع"),
                            ("QUIZ", "اختبار قصير"),
                            ("MIDTERM", "امتحان منتصف الفصل"),
                            ("FINAL", "امتحان نهائي"),
                            ("LAB", "تجربة معملية"),
                            ("PRESENTATION", "عرض تقديمي"),
                            ("RESEARCH", "بحث"),
                            ("CASE_STUDY", "دراسة حالة"),
                            ("GROUP_WORK", "عمل جماعي"),
                        ],
                        max_length=20,
                        verbose_name="نوع التكليف",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="الدرجة العظمى"
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="الوزن النسبي %"
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ النشر"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="تاريخ التسليم")),
                (
                    "late_submission_allowed",
                    models.BooleanField(
                        default=True, verbose_name="السماح بالتسليم المتأخر"
                    ),
                ),
                (
                    "late_penalty_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="خصم التأخير لكل يوم",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("PUBLISHED", "منشور"),
                            ("CLOSED", "مغلق"),
                            ("GRADED", "مصحح"),
                        ],
                        default="DRAFT",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_group_assignment",
                    models.BooleanField(default=False, verbose_name="تكليف جماعي"),
                ),
                (
                    "max_group_size",
                    models.IntegerField(
                        default=1, verbose_name="الحد الأقصى لحجم المجموعة"
                    ),
                ),
                (
                    "instructions_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/instructions/",
                        verbose_name="ملف التعليمات",
                    ),
                ),
                (
                    "submission_format",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="تنسيق التسليم المطلوب"
                    ),
                ),
                (
                    "rubric",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="معايير التقييم"
                    ),
                ),
                (
                    "estimated_time_hours",
                    models.IntegerField(
                        default=2, verbose_name="الوقت المقدر بالساعات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تكليف",
                "verbose_name_plural": "التكليفات",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القاعة")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز القاعة"
                    ),
                ),
                (
                    "classroom_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "قاعة محاضرات"),
                            ("LAB", "مختبر"),
                            ("COMPUTER_LAB", "مختبر حاسوب"),
                            ("SEMINAR", "قاعة ندوات"),
                            ("AUDITORIUM", "مدرج"),
                            ("WORKSHOP", "ورشة"),
                            ("STUDIO", "استوديو"),
                        ],
                        max_length=15,
                        verbose_name="نوع القاعة",
                    ),
                ),
                ("building", models.CharField(max_length=100, verbose_name="المبنى")),
                ("floor", models.CharField(max_length=50, verbose_name="الطابق")),
                (
                    "room_number",
                    models.CharField(max_length=20, verbose_name="رقم الغرفة"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="السعة",
                    ),
                ),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="المساحة (متر مربع)",
                    ),
                ),
                (
                    "has_projector",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على بروجيكتر"
                    ),
                ),
                (
                    "has_computer",
                    models.BooleanField(default=False, verbose_name="يحتوي على حاسوب"),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(
                        default=True, verbose_name="يحتوي على لوح أبيض"
                    ),
                ),
                (
                    "has_blackboard",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على لوح أسود"
                    ),
                ),
                (
                    "has_ac",
                    models.BooleanField(default=True, verbose_name="يحتوي على تكييف"),
                ),
                (
                    "has_wifi",
                    models.BooleanField(default=True, verbose_name="يحتوي على واي فاي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متاحة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعة دراسية",
                "verbose_name_plural": "القاعات الدراسية",
                "ordering": ["building", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الكلية - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم الكلية - إنجليزي"
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="رمز الكلية")),
                ("established_year", models.IntegerField(verbose_name="سنة التأسيس")),
                (
                    "building",
                    models.CharField(blank=True, max_length=100, verbose_name="المبنى"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=50, verbose_name="الدور"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "total_departments",
                    models.IntegerField(default=0, verbose_name="عدد الأقسام"),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="عدد الطلاب"),
                ),
                (
                    "total_faculty",
                    models.IntegerField(
                        default=0, verbose_name="عدد أعضاء هيئة التدريس"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "كلية",
                "verbose_name_plural": "الكليات",
                "ordering": ["university", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="رمز المقرر"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم المقرر - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم المقرر - إنجليزي"
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("CORE", "متطلب أساسي"),
                            ("MAJOR_REQUIRED", "متطلب تخصص"),
                            ("MAJOR_ELECTIVE", "اختياري تخصص"),
                            ("UNIVERSITY_REQUIRED", "متطلب جامعة"),
                            ("UNIVERSITY_ELECTIVE", "اختياري جامعة"),
                            ("FREE_ELECTIVE", "اختياري حر"),
                            ("REMEDIAL", "استدراكي"),
                        ],
                        max_length=20,
                        verbose_name="نوع المقرر",
                    ),
                ),
                (
                    "credit_hours",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="الساعات المعتمدة",
                    ),
                ),
                (
                    "theory_hours",
                    models.IntegerField(default=0, verbose_name="الساعات النظرية"),
                ),
                (
                    "practical_hours",
                    models.IntegerField(default=0, verbose_name="الساعات العملية"),
                ),
                (
                    "academic_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="المستوى الأكاديمي",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "مبتدئ"),
                            ("INTERMEDIATE", "متوسط"),
                            ("ADVANCED", "متقدم"),
                            ("EXPERT", "خبير"),
                        ],
                        default="INTERMEDIATE",
                        max_length=15,
                        verbose_name="مستوى الصعوبة",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("FACE_TO_FACE", "وجهاً لوجه"),
                            ("ONLINE", "إلكتروني"),
                            ("HYBRID", "مختلط"),
                            ("LABORATORY", "معملي"),
                            ("FIELD_WORK", "عمل ميداني"),
                        ],
                        default="FACE_TO_FACE",
                        max_length=15,
                        verbose_name="طريقة التدريس",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف المقرر")),
                ("objectives", models.TextField(verbose_name="أهداف المقرر")),
                ("learning_outcomes", models.TextField(verbose_name="مخرجات التعلم")),
                (
                    "course_outline",
                    models.TextField(blank=True, verbose_name="مفردات المقرر"),
                ),
                (
                    "min_gpa_required",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=4,
                        verbose_name="الحد الأدنى للمعدل المطلوب",
                    ),
                ),
                (
                    "assessment_methods",
                    models.JSONField(default=dict, verbose_name="طرق التقييم"),
                ),
                (
                    "has_final_exam",
                    models.BooleanField(
                        default=True, verbose_name="يحتوي على امتحان نهائي"
                    ),
                ),
                (
                    "has_midterm_exam",
                    models.BooleanField(
                        default=True, verbose_name="يحتوي على امتحان منتصف الفصل"
                    ),
                ),
                (
                    "textbook",
                    models.TextField(blank=True, verbose_name="الكتاب المقرر"),
                ),
                ("references", models.TextField(blank=True, verbose_name="المراجع")),
                (
                    "online_resources",
                    models.URLField(blank=True, verbose_name="المصادر الإلكترونية"),
                ),
                (
                    "max_enrollment",
                    models.IntegerField(default=50, verbose_name="الحد الأقصى للتسجيل"),
                ),
                (
                    "min_enrollment",
                    models.IntegerField(default=10, verbose_name="الحد الأدنى للتسجيل"),
                ),
                (
                    "allows_waitlist",
                    models.BooleanField(
                        default=True, verbose_name="يسمح بقائمة الانتظار"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_offered_online",
                    models.BooleanField(default=False, verbose_name="متاح إلكترونياً"),
                ),
                (
                    "requires_lab",
                    models.BooleanField(default=False, verbose_name="يتطلب معمل"),
                ),
                (
                    "requires_field_work",
                    models.BooleanField(default=False, verbose_name="يتطلب عمل ميداني"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "مقرر دراسي",
                "verbose_name_plural": "المقررات الدراسية",
                "ordering": ["department", "academic_level", "code"],
            },
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "مدرس رئيسي"),
                            ("SECONDARY", "مدرس مساعد"),
                            ("ASSISTANT", "مساعد تدريس"),
                            ("GUEST", "مدرس زائر"),
                        ],
                        default="SECONDARY",
                        max_length=15,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "can_grade",
                    models.BooleanField(default=True, verbose_name="يمكنه التقييم"),
                ),
                (
                    "can_manage_assignments",
                    models.BooleanField(
                        default=False, verbose_name="يمكنه إدارة التكليفات"
                    ),
                ),
                (
                    "can_manage_attendance",
                    models.BooleanField(
                        default=True, verbose_name="يمكنه إدارة الحضور"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرس المقرر",
                "verbose_name_plural": "مدرسو المقررات",
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_number",
                    models.CharField(max_length=10, verbose_name="رقم الشعبة"),
                ),
                (
                    "section_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم الشعبة"
                    ),
                ),
                (
                    "schedule_days",
                    models.JSONField(default=list, verbose_name="أيام التدريس"),
                ),
                ("start_time", models.TimeField(verbose_name="وقت البداية")),
                ("end_time", models.TimeField(verbose_name="وقت النهاية")),
                (
                    "classroom",
                    models.CharField(blank=True, max_length=50, verbose_name="القاعة"),
                ),
                (
                    "building",
                    models.CharField(blank=True, max_length=50, verbose_name="المبنى"),
                ),
                (
                    "max_enrollment",
                    models.IntegerField(verbose_name="الحد الأقصى للتسجيل"),
                ),
                (
                    "current_enrollment",
                    models.IntegerField(default=0, verbose_name="عدد المسجلين الحالي"),
                ),
                (
                    "waitlist_capacity",
                    models.IntegerField(default=10, verbose_name="سعة قائمة الانتظار"),
                ),
                (
                    "current_waitlist",
                    models.IntegerField(
                        default=0, verbose_name="عدد قائمة الانتظار الحالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "مجدول"),
                            ("ACTIVE", "نشط"),
                            ("COMPLETED", "مكتمل"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "registration_open",
                    models.BooleanField(default=True, verbose_name="التسجيل مفتوح"),
                ),
                (
                    "special_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات خاصة"),
                ),
                (
                    "prerequisites_enforced",
                    models.BooleanField(
                        default=True, verbose_name="فرض المتطلبات السابقة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "عرض مقرر",
                "verbose_name_plural": "عروض المقررات",
                "ordering": ["semester", "course__code", "section_number"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم القسم - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم القسم - إنجليزي"
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="رمز القسم")),
                ("established_year", models.IntegerField(verbose_name="سنة التأسيس")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="الموقع"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف القسم"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد القسم الإلكتروني"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="موقع القسم")),
                (
                    "objectives",
                    models.TextField(blank=True, verbose_name="أهداف القسم"),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="عدد الطلاب"),
                ),
                (
                    "total_faculty",
                    models.IntegerField(
                        default=0, verbose_name="عدد أعضاء هيئة التدريس"
                    ),
                ),
                (
                    "total_majors",
                    models.IntegerField(default=0, verbose_name="عدد التخصصات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قسم أكاديمي",
                "verbose_name_plural": "الأقسام الأكاديمية",
                "ordering": ["college", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم التخصص - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم التخصص - إنجليزي"
                    ),
                ),
                ("code", models.CharField(max_length=15, verbose_name="رمز التخصص")),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("DIPLOMA", "دبلوم"),
                            ("ASSOCIATE", "درجة مشارك"),
                            ("BACHELOR", "بكالوريوس"),
                            ("MASTER", "ماجستير"),
                            ("DOCTORATE", "دكتوراه"),
                            ("CERTIFICATE", "شهادة"),
                        ],
                        max_length=15,
                        verbose_name="نوع الدرجة",
                    ),
                ),
                (
                    "duration_years",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="مدة الدراسة بالسنوات",
                    ),
                ),
                (
                    "total_credit_hours",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="إجمالي الساعات المعتمدة",
                    ),
                ),
                (
                    "min_gpa_requirement",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=4,
                        verbose_name="الحد الأدنى للمعدل المطلوب",
                    ),
                ),
                (
                    "max_students_per_year",
                    models.IntegerField(
                        default=100, verbose_name="الحد الأقصى للطلاب سنوياً"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف التخصص")),
                (
                    "career_prospects",
                    models.TextField(blank=True, verbose_name="الفرص الوظيفية"),
                ),
                (
                    "admission_requirements",
                    models.TextField(blank=True, verbose_name="متطلبات القبول"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majors",
                        to="courses.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصص",
                "verbose_name_plural": "التخصصات",
                "ordering": ["department", "degree_type", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الجامعة - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم الجامعة - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="رمز الجامعة"
                    ),
                ),
                ("founded_year", models.IntegerField(verbose_name="سنة التأسيس")),
                (
                    "university_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "حكومية"),
                            ("PRIVATE", "خاصة"),
                            ("NONPROFIT", "غير ربحية"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="نوع الجامعة",
                    ),
                ),
                ("address", models.TextField(verbose_name="العنوان")),
                ("phone", models.CharField(max_length=20, verbose_name="الهاتف")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "academic_calendar_type",
                    models.CharField(
                        choices=[
                            ("SEMESTER", "فصلي"),
                            ("QUARTER", "ربع سنوي"),
                            ("TRIMESTER", "ثلاثي"),
                        ],
                        default="SEMESTER",
                        max_length=15,
                        verbose_name="نظام التقويم الأكاديمي",
                    ),
                ),
                (
                    "grading_system",
                    models.CharField(
                        choices=[
                            ("GPA_4", "نظام 4.0"),
                            ("GPA_5", "نظام 5.0"),
                            ("PERCENTAGE", "النسبة المئوية"),
                        ],
                        default="GPA_4",
                        max_length=15,
                        verbose_name="نظام التقدير",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="university_logos/",
                        verbose_name="شعار الجامعة",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الجامعة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "جامعة",
                "verbose_name_plural": "الجامعات",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semester_type",
                    models.CharField(
                        choices=[
                            ("FALL", "الفصل الأول"),
                            ("SPRING", "الفصل الثاني"),
                            ("SUMMER", "الفصل الصيفي"),
                            ("INTENSIVE", "فصل مكثف"),
                        ],
                        max_length=10,
                        verbose_name="نوع الفصل",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ بداية الفصل")),
                ("end_date", models.DateField(verbose_name="تاريخ نهاية الفصل")),
                (
                    "registration_start_date",
                    models.DateField(verbose_name="تاريخ بداية التسجيل"),
                ),
                (
                    "registration_end_date",
                    models.DateField(verbose_name="تاريخ نهاية التسجيل"),
                ),
                (
                    "add_drop_deadline",
                    models.DateField(verbose_name="آخر موعد للإضافة والحذف"),
                ),
                (
                    "withdrawal_deadline",
                    models.DateField(verbose_name="آخر موعد للانسحاب"),
                ),
                (
                    "midterm_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية امتحانات منتصف الفصل"
                    ),
                ),
                (
                    "midterm_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية امتحانات منتصف الفصل"
                    ),
                ),
                (
                    "final_exam_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية الامتحانات النهائية"
                    ),
                ),
                (
                    "final_exam_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية الامتحانات النهائية"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="الفصل الحالي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "registration_open",
                    models.BooleanField(default=False, verbose_name="التسجيل مفتوح"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="courses.academicyear",
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["-academic_year__year", "semester_type"],
            },
        ),
        migrations.CreateModel(
            name="MajorCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="مطلوب"),
                ),
                (
                    "semester_offered",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="الفصل المُقدم فيه",
                    ),
                ),
                (
                    "year_offered",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="السنة المُقدم فيها",
                    ),
                ),
                (
                    "sequence_order",
                    models.IntegerField(default=1, verbose_name="ترتيب المتسلسل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.major",
                        verbose_name="التخصص",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقرر التخصص",
                "verbose_name_plural": "مقررات التخصصات",
                "ordering": [
                    "major",
                    "year_offered",
                    "semester_offered",
                    "sequence_order",
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "مسجل"),
                            ("WAITLISTED", "قائمة انتظار"),
                            ("DROPPED", "منسحب"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "راسب"),
                            ("WITHDRAWN", "منسحب نهائياً"),
                        ],
                        default="ENROLLED",
                        max_length=15,
                        verbose_name="حالة التسجيل",
                    ),
                ),
                (
                    "midterm_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درجة منتصف الفصل",
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="الدرجة النهائية",
                    ),
                ),
                (
                    "total_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="الدرجة الإجمالية",
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("F", "F"),
                            ("I", "غير مكتمل"),
                            ("W", "منسحب"),
                            ("P", "ناجح"),
                            ("NP", "راسب"),
                        ],
                        max_length=2,
                        verbose_name="الدرجة الحرفية",
                    ),
                ),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="نقاط الدرجة",
                    ),
                ),
                (
                    "total_absences",
                    models.IntegerField(default=0, verbose_name="إجمالي الغياب"),
                ),
                (
                    "excused_absences",
                    models.IntegerField(default=0, verbose_name="الغياب المعذور"),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة الحضور",
                    ),
                ),
                (
                    "drop_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.courseoffering",
                        verbose_name="عرض المقرر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسجيل مقرر",
                "verbose_name_plural": "تسجيلات المقررات",
                "ordering": ["-enrollment_date"],
            },
        ),
    ]
