# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مُسجل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="courses.college",
                verbose_name="الكلية",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments_as_head",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رئيس القسم",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="vice_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments_as_vice_head",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نائب رئيس القسم",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="co_instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_instructor_offerings",
                through="courses.CourseInstructor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرسون المساعدون",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerings",
                to="courses.course",
                verbose_name="المقرر",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_offerings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_offerings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرس",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_offerings",
                to="courses.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AddField(
            model_name="courseinstructor",
            name="course_offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseoffering",
                verbose_name="عرض المقرر",
            ),
        ),
        migrations.AddField(
            model_name="courseinstructor",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرس",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="منسق المقرر",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="corequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="corequisite_for",
                to="courses.course",
                verbose_name="المتطلبات المصاحبة",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.department",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="majors",
            field=models.ManyToManyField(
                related_name="courses",
                through="courses.MajorCourse",
                to="courses.major",
                verbose_name="التخصصات",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="course_prerequisite_for",
                to="courses.course",
                verbose_name="المتطلبات السابقة",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="dean",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colleges_as_dean",
                to=settings.AUTH_USER_MODEL,
                verbose_name="العميد",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colleges",
                to="courses.university",
                verbose_name="الجامعة",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="vice_dean_academic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colleges_as_vice_dean_academic",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وكيل الكلية للشؤون الأكاديمية",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="vice_dean_graduate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colleges_as_vice_dean_graduate",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وكيل الكلية للدراسات العليا",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["classroom_type", "is_active"],
                name="courses_cla_classro_ce7aba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["building", "floor"], name="courses_cla_buildin_d0fa9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("building", "floor", "room_number")},
        ),
        migrations.AddField(
            model_name="assignment",
            name="course_offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.courseoffering",
                verbose_name="عرض المقرر",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["academic_year", "is_current"],
                name="courses_sem_academi_7a13c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["registration_open"], name="courses_sem_registr_7d4668_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "semester_type")},
        ),
        migrations.AddIndex(
            model_name="majorcourse",
            index=models.Index(
                fields=["major", "is_required"], name="courses_maj_major_i_a4e6fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="majorcourse",
            index=models.Index(
                fields=["semester_offered", "year_offered"],
                name="courses_maj_semeste_253c63_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="majorcourse",
            unique_together={("major", "course")},
        ),
        migrations.AddIndex(
            model_name="major",
            index=models.Index(
                fields=["department", "degree_type", "is_active"],
                name="courses_maj_departm_eabe44_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="major",
            unique_together={("department", "code")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="courses_enr_student_c86bf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course_offering", "status"],
                name="courses_enr_course__e9584c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["enrollment_date"], name="courses_enr_enrollm_eb8905_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course_offering")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["college", "is_active"], name="courses_dep_college_56917f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("college", "code")},
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["semester", "status"], name="courses_cou_semeste_b59b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["course", "semester"], name="courses_cou_course__2f86cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["instructor"], name="courses_cou_instruc_ae28e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseoffering",
            unique_together={("course", "semester", "section_number")},
        ),
        migrations.AlterUniqueTogether(
            name="courseinstructor",
            unique_together={("course_offering", "instructor")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["department", "course_type", "is_active"],
                name="courses_cou_departm_d13e11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["academic_level"], name="courses_cou_academi_c8b558_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["code"], name="courses_cou_code_612388_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="college",
            unique_together={("university", "code")},
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course_offering", "status"],
                name="courses_ass_course__4ad42f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["due_date"], name="courses_ass_due_dat_e405cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assignment_type"], name="courses_ass_assignm_8b6828_idx"
            ),
        ),
    ]
