# Generated by Django 4.2.16 on 2025-10-29 17:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="course_prerequisite_for",
                to="courses.course",
                verbose_name="المتطلبات السابقة",
            ),
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القاعة")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز القاعة"
                    ),
                ),
                (
                    "classroom_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "قاعة محاضرات"),
                            ("LAB", "مختبر"),
                            ("COMPUTER_LAB", "مختبر حاسوب"),
                            ("SEMINAR", "قاعة ندوات"),
                            ("AUDITORIUM", "مدرج"),
                            ("WORKSHOP", "ورشة"),
                            ("STUDIO", "استوديو"),
                        ],
                        max_length=15,
                        verbose_name="نوع القاعة",
                    ),
                ),
                ("building", models.CharField(max_length=100, verbose_name="المبنى")),
                ("floor", models.CharField(max_length=50, verbose_name="الطابق")),
                (
                    "room_number",
                    models.CharField(max_length=20, verbose_name="رقم الغرفة"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="السعة",
                    ),
                ),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="المساحة (متر مربع)",
                    ),
                ),
                (
                    "has_projector",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على بروجيكتر"
                    ),
                ),
                (
                    "has_computer",
                    models.BooleanField(default=False, verbose_name="يحتوي على حاسوب"),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(
                        default=True, verbose_name="يحتوي على لوح أبيض"
                    ),
                ),
                (
                    "has_blackboard",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على لوح أسود"
                    ),
                ),
                (
                    "has_ac",
                    models.BooleanField(default=True, verbose_name="يحتوي على تكييف"),
                ),
                (
                    "has_wifi",
                    models.BooleanField(default=True, verbose_name="يحتوي على واي فاي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متاحة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعة دراسية",
                "verbose_name_plural": "القاعات الدراسية",
                "ordering": ["building", "floor", "room_number"],
                "indexes": [
                    models.Index(
                        fields=["classroom_type", "is_active"],
                        name="courses_cla_classro_ce7aba_idx",
                    ),
                    models.Index(
                        fields=["building", "floor"],
                        name="courses_cla_buildin_d0fa9b_idx",
                    ),
                ],
                "unique_together": {("building", "floor", "room_number")},
            },
        ),
    ]
