name: university_app
description: نظام إدارة الجامعة - تطبيق الطلاب والأساتذة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.1
  
  # Network & API
  http: ^1.1.0
  dio: ^5.3.4
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  
  # QR Code & Barcode
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  
  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # Date & Time
  intl: ^0.18.1
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Utils
  url_launcher: ^6.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  
  # Localization
  flutter_localizations:
    sdk: flutter
    
  # PDF & Documents
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Animations
  lottie: ^2.7.0
  animate_do: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700