# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cyber_security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbehaviorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="threatintelligence",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_threat_intel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="securitythreat",
            name="affected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_threats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المتأثر",
            ),
        ),
        migrations.AddField(
            model_name="securitythreat",
            name="assigned_analyst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_threats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المحلل المكلف",
            ),
        ),
        migrations.AddField(
            model_name="securityrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_security_rules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="applies_to_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_policies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ينطبق على المستخدمين",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_security_policies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مُعتمد من",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cyber_security_policies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="affected_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدمون المتأثرون",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="incident_commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commanded_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="قائد الحادث",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="related_threats",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                to="cyber_security.securitythreat",
                verbose_name="التهديدات المرتبطة",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المُبلغ",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="response_team",
            field=models.ManyToManyField(
                blank=True,
                related_name="response_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فريق الاستجابة",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="affected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_events_affected",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المتأثر",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_security_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مُعيّن إلى",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="detected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detected_security_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اكتُشِف بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="securitydashboard",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المالك",
            ),
        ),
        migrations.AddField(
            model_name="securitydashboard",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewable_security_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المشاهدون",
            ),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="behavioranalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="threatintelligence",
            index=models.Index(
                fields=["intel_type", "confidence_level"],
                name="cyber_secur_intel_t_c55708_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="threatintelligence",
            index=models.Index(fields=["source"], name="cyber_secur_source_d0f5be_idx"),
        ),
        migrations.AddIndex(
            model_name="threatintelligence",
            index=models.Index(
                fields=["threat_score"], name="cyber_secur_threat__173ef8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threatintelligence",
            index=models.Index(
                fields=["valid_from", "valid_until"],
                name="cyber_secur_valid_f_4d02e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="threatintelligence",
            index=models.Index(
                fields=["tlp_level"], name="cyber_secur_tlp_lev_1b489c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitythreat",
            index=models.Index(
                fields=["threat_type", "severity_level"],
                name="cyber_secur_threat__98c48b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitythreat",
            index=models.Index(
                fields=["source_ip"], name="cyber_secur_source__8d7f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitythreat",
            index=models.Index(fields=["status"], name="cyber_secur_status_540fcb_idx"),
        ),
        migrations.AddIndex(
            model_name="securitythreat",
            index=models.Index(
                fields=["first_detected"], name="cyber_secur_first_d_f12d1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitythreat",
            index=models.Index(
                fields=["affected_user"], name="cyber_secur_affecte_d4cfb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["category", "is_active"], name="cyber_secur_categor_8a896e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(fields=["code"], name="cyber_secur_code_75d1d0_idx"),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["enforcement_level"], name="cyber_secur_enforce_6e7081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["effective_from", "effective_until"],
                name="cyber_secur_effecti_e9e07b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["incident_type", "status"],
                name="cyber_secur_inciden_4db7c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["impact_level"], name="cyber_secur_impact__14ac3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["occurred_at"], name="cyber_secur_occurre_2641b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["reporter"], name="cyber_secur_reporte_7cf698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["event_type", "severity"], name="cyber_secur_event_t_c8825f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["status", "created_at"], name="cyber_secur_status_ff5f64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["source_ip"], name="cyber_secur_source__ef6543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["affected_user"], name="cyber_secur_affecte_2df7b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydashboard",
            index=models.Index(
                fields=["owner", "is_active"], name="cyber_secur_owner_i_c659c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydashboard",
            index=models.Index(
                fields=["dashboard_type"], name="cyber_secur_dashboa_faa987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["event_type", "severity"], name="cyber_secur_event_t_51089c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="cyber_secur_user_id_e9ab90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["ip_address"], name="cyber_secur_ip_addr_375daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["was_successful"], name="cyber_secur_was_suc_15df92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["risk_score"], name="cyber_secur_risk_sc_389229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["timestamp"], name="cyber_secur_timesta_bf341e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behavioranalysis",
            index=models.Index(
                fields=["user", "behavior_type"], name="cyber_secur_user_id_90040d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behavioranalysis",
            index=models.Index(
                fields=["anomaly_level"], name="cyber_secur_anomaly_526288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behavioranalysis",
            index=models.Index(
                fields=["is_flagged"], name="cyber_secur_is_flag_824eb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behavioranalysis",
            index=models.Index(
                fields=["analysis_period_start", "analysis_period_end"],
                name="cyber_secur_analysi_e60790_idx",
            ),
        ),
    ]
