name: university_management
description: نظام إدارة الجامعة المتقدم - تطبيق جوال شامل ومتطور

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI وUX متقدم
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  lottie: ^3.1.0
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  
  # إدارة الحالة المتقدمة
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # الشبكة والAPI
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  
  # التخزين المحلي
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # المصادقة والأمان
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  local_auth: ^2.1.7
  biometric_storage: ^5.1.1
  flutter_secure_storage: ^9.0.0
  
  # الملاحة والتوجيه
  go_router: ^12.1.3
  auto_route: ^7.9.2
  
  # الوسائط والملفات
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  pdf_viewer_plugin: ^2.0.1
  open_file: ^3.3.2
  path_provider: ^2.1.1
  
  # الرسوم البيانية والتحليلات
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_calendar: ^24.1.41
  syncfusion_flutter_datagrid: ^24.1.41
  
  # التاريخ والوقت
  intl: ^0.19.0
  timezone: ^0.9.2
  jiffy: ^6.2.1
  
  # الإشعارات
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # المسح الضوئي والQR
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.3.0
  
  # الخرائط والموقع
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  
  # التدويل واللغات
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3
  
  # الأدوات المساعدة
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  permission_handler: ^11.1.0
  
  # التحقق من صحة البيانات
  formz: ^0.6.1
  validators: ^3.0.0
  
  # الشات والمساعد الذكي
  dash_chat_2: ^0.0.20
  flutter_chat_ui: ^1.6.10
  speech_to_text: ^6.6.0
  text_to_speech: ^0.2.3
  
  # الأداء والتحسين
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  
  # الاختبار والتطوير
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # أدوات البناء والتوليد
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2
  
  # التحليل والجودة
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  
  # الاختبار
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  
  # أدوات الأصول
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  generate: true

  # الأصول والموارد
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/images/placeholders/
    - assets/images/illustrations/
    - assets/animations/
    - assets/translations/
    - assets/fonts/
    - assets/data/

  # الخطوط المخصصة
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
    
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/gen/
  line_length: 80
  
  integrations:
    flutter_svg: true
    lottie: true

flutter_native_splash:
  color: "#1976D2"
  image: assets/images/logos/app_logo.png
  color_dark: "#121212"
  image_dark: assets/images/logos/app_logo_dark.png
  android_12:
    image: assets/images/logos/app_logo_android12.png
    icon_background_color: "#1976D2"
    image_dark: assets/images/logos/app_logo_android12_dark.png
    icon_background_color_dark: "#121212"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logos/app_icon.png"
    background_color: "#1976D2"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/images/logos/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logos/app_icon.png"