# Generated by Django 4.2.16 on 2025-10-29 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "طبي"),
                            ("EMERGENCY", "طارئ"),
                            ("OFFICIAL", "رسمي"),
                            ("TECHNICAL", "تقني"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=15,
                        verbose_name="نوع الاستثناء",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب الاستثناء")),
                (
                    "supporting_documents",
                    models.JSONField(default=list, verbose_name="المستندات الداعمة"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقديم"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="تاريخ السريان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("APPROVED", "موافق عليه"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "reviewer_comments",
                    models.TextField(blank=True, verbose_name="تعليقات المراجع"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "استثناء حضور وغياب",
                "verbose_name_plural": "استثناءات الحضور والغياب",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "حاضر"),
                            ("ABSENT", "غائب"),
                            ("LATE", "متأخر"),
                            ("EXCUSED", "معذور"),
                            ("EARLY_DEPARTURE", "انصراف مبكر"),
                        ],
                        max_length=20,
                        verbose_name="حالة الحضور",
                    ),
                ),
                (
                    "attendance_method",
                    models.CharField(
                        choices=[
                            ("QR_CODE", "رمز QR"),
                            ("MANUAL", "يدوي"),
                            ("FACIAL_RECOGNITION", "التعرف على الوجه"),
                            ("FINGERPRINT", "بصمة الإصبع"),
                            ("RFID", "RFID"),
                            ("PROXIMITY", "القرب"),
                            ("OTHER", "أخرى"),
                        ],
                        default="QR_CODE",
                        max_length=20,
                        verbose_name="طريقة الحضور",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التسجيل"),
                ),
                (
                    "arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الوصول"
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانصراف"
                    ),
                ),
                (
                    "scan_location_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="خط عرض المسح",
                    ),
                ),
                (
                    "scan_location_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="خط طول المسح",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="معلومات الجهاز"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="مُتحقق منه"),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="طريقة التحقق"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التحقق"
                    ),
                ),
                (
                    "attendance_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="نقاط الحضور",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="نقاط إضافية",
                    ),
                ),
                (
                    "penalty_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="نقاط الخصم",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "excuse_reason",
                    models.TextField(blank=True, verbose_name="سبب العذر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سجل حضور وغياب",
                "verbose_name_plural": "سجلات الحضور والغياب",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_name",
                    models.CharField(max_length=200, verbose_name="اسم التقرير"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_SUMMARY", "ملخص طالب"),
                            ("COURSE_SUMMARY", "ملخص مقرر"),
                            ("INSTRUCTOR_SUMMARY", "ملخص مدرس"),
                            ("DAILY_REPORT", "تقرير يومي"),
                            ("WEEKLY_REPORT", "تقرير أسبوعي"),
                            ("MONTHLY_REPORT", "تقرير شهري"),
                            ("SEMESTER_REPORT", "تقرير فصلي"),
                            ("CUSTOM_REPORT", "تقرير مخصص"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="إجمالي الجلسات"),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="إجمالي الطلاب"),
                ),
                (
                    "average_attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="متوسط معدل الحضور",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(default=dict, verbose_name="بيانات التقرير"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "قيد الإنتاج"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "فاشل"),
                        ],
                        default="GENERATING",
                        max_length=15,
                        verbose_name="حالة التقرير",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الملف"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإنتاج"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تقرير حضور وغياب",
                "verbose_name_plural": "تقارير الحضور والغياب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_name",
                    models.CharField(max_length=200, verbose_name="اسم الجلسة"),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "محاضرة"),
                            ("LAB", "معمل"),
                            ("TUTORIAL", "تطبيق"),
                            ("SEMINAR", "ندوة"),
                            ("EXAM", "امتحان"),
                            ("EVENT", "فعالية"),
                            ("OTHER", "أخرى"),
                        ],
                        default="LECTURE",
                        max_length=15,
                        verbose_name="نوع الجلسة",
                    ),
                ),
                (
                    "scheduled_start_time",
                    models.DateTimeField(verbose_name="وقت البداية المُجدول"),
                ),
                (
                    "scheduled_end_time",
                    models.DateTimeField(verbose_name="وقت النهاية المُجدول"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت البداية الفعلي"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت النهاية الفعلي"
                    ),
                ),
                (
                    "location_coordinates",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="إحداثيات الموقع"
                    ),
                ),
                (
                    "attendance_window_minutes",
                    models.IntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="نافزة الحضور (دقائق)",
                    ),
                ),
                (
                    "late_threshold_minutes",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="حد التأخير (دقائق)",
                    ),
                ),
                (
                    "qr_code_type",
                    models.CharField(
                        choices=[
                            ("STATIC", "ثابت"),
                            ("DYNAMIC", "ديناميكي"),
                            ("TIME_BASED", "مؤقت"),
                            ("LOCATION_BASED", "مكاني"),
                        ],
                        default="DYNAMIC",
                        max_length=15,
                        verbose_name="نوع رمز QR",
                    ),
                ),
                (
                    "qr_code_refresh_minutes",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="تحديث رمز QR (دقائق)",
                    ),
                ),
                (
                    "qr_code_range_meters",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="نطاق رمز QR (متر)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "مُجدولة"),
                            ("ACTIVE", "نشطة"),
                            ("COMPLETED", "مكتملة"),
                            ("CANCELLED", "ملغية"),
                            ("POSTPONED", "مؤجلة"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                        verbose_name="حالة الجلسة",
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="إجمالي الطلاب"),
                ),
                (
                    "present_count",
                    models.IntegerField(default=0, verbose_name="عدد الحاضرين"),
                ),
                (
                    "late_count",
                    models.IntegerField(default=0, verbose_name="عدد المتأخرين"),
                ),
                (
                    "absent_count",
                    models.IntegerField(default=0, verbose_name="عدد الغائبين"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الجلسة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "جلسة حضور وغياب",
                "verbose_name_plural": "جلسات الحضور والغياب",
                "ordering": ["-scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "default_attendance_window_minutes",
                    models.IntegerField(
                        default=15, verbose_name="نافذة الحضور الافتراضية (دقائق)"
                    ),
                ),
                (
                    "default_late_threshold_minutes",
                    models.IntegerField(
                        default=10, verbose_name="حد التأخير الافتراضي (دقائق)"
                    ),
                ),
                (
                    "qr_code_refresh_minutes",
                    models.IntegerField(default=5, verbose_name="تحديث رمز QR (دقائق)"),
                ),
                (
                    "qr_code_valid_range_meters",
                    models.IntegerField(
                        default=50, verbose_name="نطاق صلاحية رمز QR (متر)"
                    ),
                ),
                (
                    "enable_location_verification",
                    models.BooleanField(
                        default=True, verbose_name="تفعيل التحقق من الموقع"
                    ),
                ),
                (
                    "present_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="نقاط الحضور",
                    ),
                ),
                (
                    "late_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="نقاط التأخير",
                    ),
                ),
                (
                    "excused_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="نقاط العذر",
                    ),
                ),
                (
                    "absent_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="نقاط الغياب",
                    ),
                ),
                (
                    "enable_attendance_reminders",
                    models.BooleanField(
                        default=True, verbose_name="تفعيل تذكيرات الحضور"
                    ),
                ),
                (
                    "reminder_minutes_before",
                    models.IntegerField(default=30, verbose_name="التذكير قبل (دقائق)"),
                ),
                (
                    "auto_generate_reports",
                    models.BooleanField(
                        default=True, verbose_name="إنتاج تقارير تلقائي"
                    ),
                ),
                (
                    "report_generation_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "يومي"),
                            ("WEEKLY", "أسبوعي"),
                            ("MONTHLY", "شهري"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                        verbose_name="تكرار إنتاج التقارير",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات الحضور والغياب",
                "verbose_name_plural": "إعدادات الحضور والغياب",
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_code_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="معرف رمز QR"
                    ),
                ),
                ("qr_data", models.TextField(verbose_name="بيانات رمز QR")),
                (
                    "secret_key",
                    models.CharField(max_length=255, verbose_name="المفتاح السري"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاريخ الانتهاء")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("EXPIRED", "منتهي"),
                            ("USED", "مُستخدم"),
                            ("DISABLED", "معطل"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="حالة الرمز",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="عدد مرات الاستخدام"),
                ),
                (
                    "max_usage",
                    models.IntegerField(
                        default=1, verbose_name="الحد الأقصى للاستخدام"
                    ),
                ),
                (
                    "valid_location_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="خط العرض الصالح",
                    ),
                ),
                (
                    "valid_location_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="خط الطول الصالح",
                    ),
                ),
                (
                    "location_radius_meters",
                    models.IntegerField(default=50, verbose_name="نطاق الموقع (متر)"),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="صورة رمز QR",
                    ),
                ),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="attendance_qr.attendancesession",
                        verbose_name="جلسة الحضور",
                    ),
                ),
            ],
            options={
                "verbose_name": "رمز QR",
                "verbose_name_plural": "رموز QR",
                "ordering": ["-created_at"],
            },
        ),
    ]
