# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance_qr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_attendance_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.classroom",
                verbose_name="القاعة الدراسية",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="course_offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_sessions",
                to="courses.courseoffering",
                verbose_name="عرض المقرر",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_attendance_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرس",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="course_offerings",
            field=models.ManyToManyField(
                blank=True, to="courses.courseoffering", verbose_name="عروض المقررات"
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_attendance_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنتج بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="instructor_attendance_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرسون",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="attendance_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطلاب",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="attendance_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendance_qr.attendancesession",
                verbose_name="جلسة الحضور",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="qr_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance_qr.qrcode",
                verbose_name="رمز QR",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_attendance_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التحقق بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="attendanceexception",
            name="attendance_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_exceptions",
                to="attendance_qr.attendancesession",
                verbose_name="جلسة الحضور",
            ),
        ),
        migrations.AddField(
            model_name="attendanceexception",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_attendance_exceptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AddField(
            model_name="attendanceexception",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_exceptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["attendance_session", "status"],
                name="attendance__attenda_418ad5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["qr_code_id"], name="attendance__qr_code_5a5610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["expires_at"], name="attendance__expires_0dc36b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["course_offering", "status"],
                name="attendance__course__590408_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["instructor"], name="attendance__instruc_b04689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["scheduled_start_time"], name="attendance__schedul_dd11ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(fields=["status"], name="attendance__status_db0401_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(
                fields=["report_type", "status"], name="attendance__report__b65ec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(
                fields=["start_date", "end_date"], name="attendance__start_d_26f1af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(
                fields=["generated_by"], name="attendance__generat_2f9610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["attendance_session", "status"],
                name="attendance__attenda_582e86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "status"], name="attendance__student_ec929f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["recorded_at"], name="attendance__recorde_95181d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["is_verified"], name="attendance__is_veri_96c599_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("attendance_session", "student")},
        ),
        migrations.AddIndex(
            model_name="attendanceexception",
            index=models.Index(
                fields=["student", "status"], name="attendance__student_5aea62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceexception",
            index=models.Index(
                fields=["attendance_session"], name="attendance__attenda_3a3e51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceexception",
            index=models.Index(
                fields=["exception_type"], name="attendance__excepti_81d4a0_idx"
            ),
        ),
    ]
