# Generated by Django 5.2.7 on 2025-11-02 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_qr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_result', models.CharField(choices=[('SUCCESS', 'نجح'), ('FAILED', 'فشل'), ('EXPIRED', 'منتهي الصلاحية'), ('INVALID', 'غير صحيح'), ('DUPLICATE', 'مكرر')], max_length=15, verbose_name='نتيجة المسح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('location_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الموقع')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المسح')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='attendance_qr.qrcode', verbose_name='رمز QR')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='مُسح بواسطة')),
            ],
            options={
                'verbose_name': 'سجل مسح QR',
                'verbose_name_plural': 'سجلات مسح QR',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['qr_code', '-scanned_at'], name='attendance__qr_code_cd4520_idx'), models.Index(fields=['scanned_by', '-scanned_at'], name='attendance__scanned_840627_idx'), models.Index(fields=['scan_result'], name='attendance__scan_re_136f80_idx')],
            },
        ),
    ]
