# Generated by Django 4.2.16 on 2025-10-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_alter_course_prerequisites_classroom"),
        ("students", "0003_alter_useractivity_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_period_start", models.DateField()),
                ("analysis_period_end", models.DateField()),
                (
                    "pattern_data",
                    models.JSONField(help_text="Analyzed study pattern data"),
                ),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("improvement_suggestions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_patterns",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "study_patterns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformancePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_grade", models.CharField(max_length=2)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "factors",
                    models.JSONField(help_text="Factors influencing the prediction"),
                ),
                ("recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_predictions",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_predictions",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "performance_predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("reasoning", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommended_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_to_students",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_recommendations",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "course_recommendations",
                "ordering": ["-recommendation_score"],
            },
        ),
    ]
