# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studypattern",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_patterns",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="performanceprediction",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_predictions",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="performanceprediction",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_predictions",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="courserecommendation",
            name="recommended_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommended_to_students",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courserecommendation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_recommendations",
                to="students.studentprofile",
            ),
        ),
    ]
