# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="معرف الجلسة"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "تسجيل دخول"),
                            ("LOGOUT", "تسجيل خروج"),
                            ("ACCESS_GRANTED", "وصول مُسمح"),
                            ("ACCESS_DENIED", "وصول مُرفض"),
                            ("PERMISSION_USED", "استخدام صلاحية"),
                            ("ROLE_CHANGED", "تغيير دور"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "action_description",
                    models.CharField(max_length=255, verbose_name="وصف الإجراء"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(verbose_name="متصفح المستخدم")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الطلب"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="طريقة الطلب"
                    ),
                ),
                ("was_successful", models.BooleanField(verbose_name="نجح الإجراء")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="مستوى المخاطر",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="سبب الفشل"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
            ],
            options={
                "verbose_name": "سجل الوصول",
                "verbose_name_plural": "سجلات الوصول",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الوحدة - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم الوحدة - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز الوحدة"
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("UNIVERSITY", "جامعة"),
                            ("COLLEGE", "كلية"),
                            ("DEPARTMENT", "قسم"),
                            ("CENTER", "مركز"),
                            ("INSTITUTE", "معهد"),
                            ("OFFICE", "مكتب"),
                        ],
                        max_length=15,
                        verbose_name="نوع الوحدة",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(default=1, verbose_name="مستوى التدرج"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "وحدة تنظيمية",
                "verbose_name_plural": "الوحدات التنظيمية",
                "ordering": ["hierarchy_level", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رمز الصلاحية"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=255, verbose_name="اسم الصلاحية - عربي"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="اسم الصلاحية - إنجليزي"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الصلاحية"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "نظام"),
                            ("ACADEMIC", "أكاديمي"),
                            ("FINANCIAL", "مالي"),
                            ("HR", "موارد بشرية"),
                            ("REPORTING", "تقارير"),
                            ("SECURITY", "أمان"),
                            ("AI", "ذكاء اصطناعي"),
                        ],
                        max_length=20,
                        verbose_name="فئة الصلاحية",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("VIEW", "عرض"),
                            ("CREATE", "إنشاء"),
                            ("UPDATE", "تعديل"),
                            ("DELETE", "حذف"),
                            ("APPROVE", "موافقة"),
                            ("MANAGE", "إدارة كاملة"),
                        ],
                        max_length=10,
                        verbose_name="مستوى الصلاحية",
                    ),
                ),
                ("priority", models.IntegerField(default=1, verbose_name="الأولوية")),
                (
                    "requires_supervisor_approval",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب موافقة المشرف"
                    ),
                ),
                (
                    "resource_constraints",
                    models.JSONField(default=dict, verbose_name="قيود الموارد"),
                ),
                (
                    "time_constraints",
                    models.JSONField(default=dict, verbose_name="قيود زمنية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_system_permission",
                    models.BooleanField(default=False, verbose_name="صلاحية نظام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "صلاحية",
                "verbose_name_plural": "الصلاحيات",
                "ordering": ["category", "priority", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="اسم الدور - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, verbose_name="اسم الدور - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز الدور"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف الدور")),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "دور نظام"),
                            ("ACADEMIC", "دور أكاديمي"),
                            ("ADMINISTRATIVE", "دور إداري"),
                            ("CUSTOM", "دور مخصص"),
                        ],
                        max_length=15,
                        verbose_name="نوع الدور",
                    ),
                ),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("SUPER", "فائق"),
                            ("HIGH", "عالي"),
                            ("MEDIUM", "متوسط"),
                            ("LOW", "منخفض"),
                            ("GUEST", "زائر"),
                        ],
                        max_length=10,
                        verbose_name="مستوى الدور",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(default=1, verbose_name="مستوى التدرج"),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى للمستخدمين"
                    ),
                ),
                (
                    "session_timeout",
                    models.IntegerField(
                        default=3600, verbose_name="انتهاء الجلسة (ثانية)"
                    ),
                ),
                (
                    "requires_2fa",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب مصادقة ثنائية"
                    ),
                ),
                (
                    "ip_restrictions",
                    models.JSONField(default=list, verbose_name="قيود عناوين IP"),
                ),
                (
                    "time_restrictions",
                    models.JSONField(default=dict, verbose_name="قيود زمنية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_system_role",
                    models.BooleanField(default=False, verbose_name="دور نظام"),
                ),
                (
                    "is_assignable",
                    models.BooleanField(default=True, verbose_name="قابل للتعيين"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "دور",
                "verbose_name_plural": "الأدوار",
                "ordering": ["hierarchy_level", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "مباشر"),
                            ("INHERITED", "موروث"),
                            ("TEMPORARY", "مؤقت"),
                            ("CONDITIONAL", "مشروط"),
                        ],
                        default="DIRECT",
                        max_length=15,
                        verbose_name="نوع المنح",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(default=dict, verbose_name="شروط الصلاحية"),
                ),
                (
                    "resource_limits",
                    models.JSONField(default=dict, verbose_name="حدود الموارد"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="ساري من"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ساري حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_inherited",
                    models.BooleanField(default=False, verbose_name="قابل للوراثة"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=False, verbose_name="يتطلب موافقة"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "صلاحية الدور",
                "verbose_name_plural": "صلاحيات الأدوار",
                "ordering": ["role", "permission__category", "permission__priority"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم السياسة - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم السياسة - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز السياسة"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف السياسة")),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "مصادقة"),
                            ("AUTHORIZATION", "تفويض"),
                            ("PASSWORD", "كلمة مرور"),
                            ("SESSION", "جلسة"),
                            ("ACCESS_CONTROL", "التحكم في الوصول"),
                            ("DATA_PROTECTION", "حماية البيانات"),
                        ],
                        max_length=20,
                        verbose_name="نوع السياسة",
                    ),
                ),
                (
                    "enforcement_level",
                    models.CharField(
                        choices=[
                            ("STRICT", "صارم"),
                            ("MODERATE", "متوسط"),
                            ("LENIENT", "متساهل"),
                            ("DISABLED", "معطل"),
                        ],
                        default="MODERATE",
                        max_length=15,
                        verbose_name="مستوى التطبيق",
                    ),
                ),
                (
                    "policy_settings",
                    models.JSONField(default=dict, verbose_name="إعدادات السياسة"),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="سارية من"
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="سارية حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_system_policy",
                    models.BooleanField(default=False, verbose_name="سياسة نظام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سياسة أمان",
                "verbose_name_plural": "سياسات الأمان",
                "ordering": ["policy_type", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="UnitMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("MEMBER", "عضو"),
                            ("COORDINATOR", "منسق"),
                            ("DEPUTY", "نائب"),
                            ("SECRETARY", "سكرتير"),
                        ],
                        default="MEMBER",
                        max_length=15,
                        verbose_name="نوع العضوية",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانضمام"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ساري حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "عضوية وحدة",
                "verbose_name_plural": "عضويات الوحدات",
                "ordering": ["unit", "membership_type", "user"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "دائم"),
                            ("TEMPORARY", "مؤقت"),
                            ("ACTING", "بالوكالة"),
                            ("SUBSTITUTE", "بديل"),
                        ],
                        default="PERMANENT",
                        max_length=15,
                        verbose_name="نوع التعيين",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التعيين"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ساري من"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ساري حتى"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("ACTIVE", "نشط"),
                            ("SUSPENDED", "موقوف"),
                            ("EXPIRED", "منتهي"),
                            ("REVOKED", "مُلغى"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="دور أساسي"),
                ),
                (
                    "assignment_reason",
                    models.TextField(blank=True, verbose_name="سبب التعيين"),
                ),
                (
                    "resource_quotas",
                    models.JSONField(default=dict, verbose_name="حصص الموارد"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإلغاء"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "additional_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_role_permissions",
                        to="roles_permissions.permission",
                        verbose_name="صلاحيات إضافية",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور المستخدم",
                "verbose_name_plural": "أدوار المستخدمين",
                "ordering": ["-is_primary", "user", "role"],
            },
        ),
    ]
