# Generated by Django 4.2.16 on 2025-10-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الوحدة - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم الوحدة - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز الوحدة"
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("UNIVERSITY", "جامعة"),
                            ("COLLEGE", "كلية"),
                            ("DEPARTMENT", "قسم"),
                            ("CENTER", "مركز"),
                            ("INSTITUTE", "معهد"),
                            ("OFFICE", "مكتب"),
                        ],
                        max_length=15,
                        verbose_name="نوع الوحدة",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(default=1, verbose_name="مستوى التدرج"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_units",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رئيس الوحدة",
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة تنظيمية",
                "verbose_name_plural": "الوحدات التنظيمية",
                "ordering": ["hierarchy_level", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رمز الصلاحية"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=255, verbose_name="اسم الصلاحية - عربي"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="اسم الصلاحية - إنجليزي"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الصلاحية"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "نظام"),
                            ("ACADEMIC", "أكاديمي"),
                            ("FINANCIAL", "مالي"),
                            ("HR", "موارد بشرية"),
                            ("REPORTING", "تقارير"),
                            ("SECURITY", "أمان"),
                            ("AI", "ذكاء اصطناعي"),
                        ],
                        max_length=20,
                        verbose_name="فئة الصلاحية",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("VIEW", "عرض"),
                            ("CREATE", "إنشاء"),
                            ("UPDATE", "تعديل"),
                            ("DELETE", "حذف"),
                            ("APPROVE", "موافقة"),
                            ("MANAGE", "إدارة كاملة"),
                        ],
                        max_length=10,
                        verbose_name="مستوى الصلاحية",
                    ),
                ),
                ("priority", models.IntegerField(default=1, verbose_name="الأولوية")),
                (
                    "requires_supervisor_approval",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب موافقة المشرف"
                    ),
                ),
                (
                    "resource_constraints",
                    models.JSONField(default=dict, verbose_name="قيود الموارد"),
                ),
                (
                    "time_constraints",
                    models.JSONField(default=dict, verbose_name="قيود زمنية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_system_permission",
                    models.BooleanField(default=False, verbose_name="صلاحية نظام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to="contenttypes.contenttype",
                        verbose_name="نوع المحتوى",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشأت بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية",
                "verbose_name_plural": "الصلاحيات",
                "ordering": ["category", "priority", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="اسم الدور - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, verbose_name="اسم الدور - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز الدور"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف الدور")),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "دور نظام"),
                            ("ACADEMIC", "دور أكاديمي"),
                            ("ADMINISTRATIVE", "دور إداري"),
                            ("CUSTOM", "دور مخصص"),
                        ],
                        max_length=15,
                        verbose_name="نوع الدور",
                    ),
                ),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("SUPER", "فائق"),
                            ("HIGH", "عالي"),
                            ("MEDIUM", "متوسط"),
                            ("LOW", "منخفض"),
                            ("GUEST", "زائر"),
                        ],
                        max_length=10,
                        verbose_name="مستوى الدور",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(default=1, verbose_name="مستوى التدرج"),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى للمستخدمين"
                    ),
                ),
                (
                    "session_timeout",
                    models.IntegerField(
                        default=3600, verbose_name="انتهاء الجلسة (ثانية)"
                    ),
                ),
                (
                    "requires_2fa",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب مصادقة ثنائية"
                    ),
                ),
                (
                    "ip_restrictions",
                    models.JSONField(default=list, verbose_name="قيود عناوين IP"),
                ),
                (
                    "time_restrictions",
                    models.JSONField(default=dict, verbose_name="قيود زمنية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_system_role",
                    models.BooleanField(default=False, verbose_name="دور نظام"),
                ),
                (
                    "is_assignable",
                    models.BooleanField(default=True, verbose_name="قابل للتعيين"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشأ بواسطة",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_roles",
                        to="roles_permissions.role",
                        verbose_name="الدور الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور",
                "verbose_name_plural": "الأدوار",
                "ordering": ["hierarchy_level", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="UnitMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("MEMBER", "عضو"),
                            ("COORDINATOR", "منسق"),
                            ("DEPUTY", "نائب"),
                            ("SECRETARY", "سكرتير"),
                        ],
                        default="MEMBER",
                        max_length=15,
                        verbose_name="نوع العضوية",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانضمام"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ساري حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="roles_permissions.organizationalunit",
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضوية وحدة",
                "verbose_name_plural": "عضويات الوحدات",
                "ordering": ["unit", "membership_type", "user"],
                "unique_together": {("unit", "user")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "مباشر"),
                            ("INHERITED", "موروث"),
                            ("TEMPORARY", "مؤقت"),
                            ("CONDITIONAL", "مشروط"),
                        ],
                        default="DIRECT",
                        max_length=15,
                        verbose_name="نوع المنح",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(default=dict, verbose_name="شروط الصلاحية"),
                ),
                (
                    "resource_limits",
                    models.JSONField(default=dict, verbose_name="حدود الموارد"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="ساري من"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ساري حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_inherited",
                    models.BooleanField(default=False, verbose_name="قابل للوراثة"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=False, verbose_name="يتطلب موافقة"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُوافق عليه من",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشأ بواسطة",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="roles_permissions.permission",
                        verbose_name="الصلاحية",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="roles_permissions.role",
                        verbose_name="الدور",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية الدور",
                "verbose_name_plural": "صلاحيات الأدوار",
                "ordering": ["role", "permission__category", "permission__priority"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="roles_permissions.RolePermission",
                to="roles_permissions.permission",
                verbose_name="الصلاحيات",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="members",
            field=models.ManyToManyField(
                related_name="organizational_units",
                through="roles_permissions.UnitMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الأعضاء",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="parent_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_units",
                to="roles_permissions.organizationalunit",
                verbose_name="الوحدة الأب",
            ),
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="معرف الجلسة"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "تسجيل دخول"),
                            ("LOGOUT", "تسجيل خروج"),
                            ("ACCESS_GRANTED", "وصول مُسمح"),
                            ("ACCESS_DENIED", "وصول مُرفض"),
                            ("PERMISSION_USED", "استخدام صلاحية"),
                            ("ROLE_CHANGED", "تغيير دور"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "action_description",
                    models.CharField(max_length=255, verbose_name="وصف الإجراء"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(verbose_name="متصفح المستخدم")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الطلب"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="طريقة الطلب"
                    ),
                ),
                ("was_successful", models.BooleanField(verbose_name="نجح الإجراء")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="مستوى المخاطر",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="سبب الفشل"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "permission_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="roles_permissions.permission",
                        verbose_name="الصلاحية المستخدمة",
                    ),
                ),
                (
                    "role_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="roles_permissions.role",
                        verbose_name="الدور المستخدم",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل الوصول",
                "verbose_name_plural": "سجلات الوصول",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "دائم"),
                            ("TEMPORARY", "مؤقت"),
                            ("ACTING", "بالوكالة"),
                            ("SUBSTITUTE", "بديل"),
                        ],
                        default="PERMANENT",
                        max_length=15,
                        verbose_name="نوع التعيين",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التعيين"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ساري من"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ساري حتى"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("ACTIVE", "نشط"),
                            ("SUSPENDED", "موقوف"),
                            ("EXPIRED", "منتهي"),
                            ("REVOKED", "مُلغى"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="دور أساسي"),
                ),
                (
                    "assignment_reason",
                    models.TextField(blank=True, verbose_name="سبب التعيين"),
                ),
                (
                    "resource_quotas",
                    models.JSONField(default=dict, verbose_name="حصص الموارد"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإلغاء"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "additional_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_role_permissions",
                        to="roles_permissions.permission",
                        verbose_name="صلاحيات إضافية",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عُين بواسطة",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُلغى بواسطة",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="roles_permissions.role",
                        verbose_name="الدور",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور المستخدم",
                "verbose_name_plural": "أدوار المستخدمين",
                "ordering": ["-is_primary", "user", "role"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="roles_permi_user_id_9b0520_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"],
                        name="roles_permi_role_id_4d2050_idx",
                    ),
                    models.Index(
                        fields=["status"], name="roles_permi_status_d9a49e_idx"
                    ),
                    models.Index(
                        fields=["assignment_type"],
                        name="roles_permi_assignm_6967bb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم السياسة - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="اسم السياسة - إنجليزي"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز السياسة"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف السياسة")),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "مصادقة"),
                            ("AUTHORIZATION", "تفويض"),
                            ("PASSWORD", "كلمة مرور"),
                            ("SESSION", "جلسة"),
                            ("ACCESS_CONTROL", "التحكم في الوصول"),
                            ("DATA_PROTECTION", "حماية البيانات"),
                        ],
                        max_length=20,
                        verbose_name="نوع السياسة",
                    ),
                ),
                (
                    "enforcement_level",
                    models.CharField(
                        choices=[
                            ("STRICT", "صارم"),
                            ("MODERATE", "متوسط"),
                            ("LENIENT", "متساهل"),
                            ("DISABLED", "معطل"),
                        ],
                        default="MODERATE",
                        max_length=15,
                        verbose_name="مستوى التطبيق",
                    ),
                ),
                (
                    "policy_settings",
                    models.JSONField(default=dict, verbose_name="إعدادات السياسة"),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="سارية من"
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="سارية حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_system_policy",
                    models.BooleanField(default=False, verbose_name="سياسة نظام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "applies_to_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="security_policies",
                        to="roles_permissions.role",
                        verbose_name="الأدوار المطبقة عليها",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_security_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشأت بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سياسة أمان",
                "verbose_name_plural": "سياسات الأمان",
                "ordering": ["policy_type", "name_ar"],
                "indexes": [
                    models.Index(
                        fields=["policy_type", "is_active"],
                        name="roles_permi_policy__583f90_idx",
                    ),
                    models.Index(fields=["code"], name="roles_permi_code_4db8f7_idx"),
                    models.Index(
                        fields=["enforcement_level"],
                        name="roles_permi_enforce_e87fd8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "is_active"], name="roles_permi_role_id_f33323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission", "is_active"],
                name="roles_permi_permiss_4f4fc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["grant_type"], name="roles_permi_grant_t_486979_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["role_type", "role_level"],
                name="roles_permi_role_ty_97ef95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="roles_permi_code_2843d5_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active", "is_assignable"],
                name="roles_permi_is_acti_606126_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["category", "level"], name="roles_permi_categor_f3440a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["codename"], name="roles_permi_codenam_28343e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["is_active"], name="roles_permi_is_acti_acc0e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(
                fields=["unit_type", "is_active"], name="roles_permi_unit_ty_366cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(
                fields=["parent_unit"], name="roles_permi_parent__f9d749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["user", "-timestamp"], name="roles_permi_user_id_d658ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["action_type"], name="roles_permi_action__9d7031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["was_successful"], name="roles_permi_was_suc_3c5aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["risk_level"], name="roles_permi_risk_le_0b95b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["ip_address"], name="roles_permi_ip_addr_7b4a70_idx"
            ),
        ),
    ]
