# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles_permissions", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عُين بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُلغى بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="roles_permissions.role",
                verbose_name="الدور",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="unitmembership",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="roles_permissions.organizationalunit",
                verbose_name="الوحدة",
            ),
        ),
        migrations.AddField(
            model_name="unitmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="applies_to_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_policies",
                to="roles_permissions.role",
                verbose_name="الأدوار المطبقة عليها",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_security_policies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_role_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مُوافق عليه من",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_role_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="roles_permissions.permission",
                verbose_name="الصلاحية",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="roles_permissions.role",
                verbose_name="الدور",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="parent_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_roles",
                to="roles_permissions.role",
                verbose_name="الدور الأب",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="roles_permissions.RolePermission",
                to="roles_permissions.permission",
                verbose_name="الصلاحيات",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_permissions",
                to="contenttypes.contenttype",
                verbose_name="نوع المحتوى",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_units",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رئيس الوحدة",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="members",
            field=models.ManyToManyField(
                related_name="organizational_units",
                through="roles_permissions.UnitMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الأعضاء",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="parent_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_units",
                to="roles_permissions.organizationalunit",
                verbose_name="الوحدة الأب",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="permission_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="roles_permissions.permission",
                verbose_name="الصلاحية المستخدمة",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="role_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="roles_permissions.role",
                verbose_name="الدور المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_active"], name="roles_permi_user_id_9b0520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["role", "is_active"], name="roles_permi_role_id_4d2050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["status"], name="roles_permi_status_d9a49e_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["assignment_type"], name="roles_permi_assignm_6967bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unitmembership",
            unique_together={("unit", "user")},
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["policy_type", "is_active"],
                name="roles_permi_policy__583f90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(fields=["code"], name="roles_permi_code_4db8f7_idx"),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["enforcement_level"], name="roles_permi_enforce_e87fd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "is_active"], name="roles_permi_role_id_f33323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission", "is_active"],
                name="roles_permi_permiss_4f4fc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["grant_type"], name="roles_permi_grant_t_486979_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["role_type", "role_level"],
                name="roles_permi_role_ty_97ef95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="roles_permi_code_2843d5_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active", "is_assignable"],
                name="roles_permi_is_acti_606126_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["category", "level"], name="roles_permi_categor_f3440a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["codename"], name="roles_permi_codenam_28343e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["is_active"], name="roles_permi_is_acti_acc0e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(
                fields=["unit_type", "is_active"], name="roles_permi_unit_ty_366cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(
                fields=["parent_unit"], name="roles_permi_parent__f9d749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["user", "-timestamp"], name="roles_permi_user_id_d658ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["action_type"], name="roles_permi_action__9d7031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["was_successful"], name="roles_permi_was_suc_3c5aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["risk_level"], name="roles_permi_risk_le_0b95b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["ip_address"], name="roles_permi_ip_addr_7b4a70_idx"
            ),
        ),
    ]
