# Generated by Django 4.2.16 on 2025-10-29 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        default="personal",
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="رابط الإجراء"),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نص الإجراء"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إشعار داخل التطبيق",
                "verbose_name_plural": "الإشعارات داخل التطبيق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        default="personal",
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="رابط الإجراء"),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نص الإجراء"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                            ("WHATSAPP", "WhatsApp"),
                            ("TELEGRAM", "Telegram"),
                            ("SLACK", "Slack"),
                            ("DISCORD", "Discord"),
                            ("WEBHOOK", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Channel-specific configuration (API keys, endpoints, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("daily_limit", models.IntegerField(blank=True, null=True)),
                ("hourly_limit", models.IntegerField(blank=True, null=True)),
                ("total_sent", models.BigIntegerField(default=0)),
                ("total_delivered", models.BigIntegerField(default=0)),
                ("total_failed", models.BigIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_channels_enhanced",
                "ordering": ["channel_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "بريد إلكتروني"),
                            ("SMS", "رسالة نصية"),
                            ("PUSH", "إشعار فوري"),
                            ("IN_APP", "داخل التطبيق"),
                        ],
                        max_length=10,
                        verbose_name="قناة التسليم",
                    ),
                ),
                (
                    "recipient_address",
                    models.CharField(max_length=255, verbose_name="عنوان المستلم"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "في الانتظار"),
                            ("SENT", "مُرسل"),
                            ("DELIVERED", "مُسلم"),
                            ("FAILED", "فاشل"),
                            ("BOUNCED", "مرتد"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="حالة التسليم",
                    ),
                ),
                (
                    "delivery_attempts",
                    models.IntegerField(default=0, verbose_name="محاولات التسليم"),
                ),
                (
                    "response_data",
                    models.JSONField(default=dict, verbose_name="بيانات الاستجابة"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التسليم"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تسليم إشعار",
                "verbose_name_plural": "تسليمات الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(max_length=100, verbose_name="معرف القالب"),
                ),
                (
                    "recipient_user_id",
                    models.CharField(max_length=50, verbose_name="معرف المستلم"),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد المستلم"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف المستلم"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "channels_used",
                    models.JSONField(default=list, verbose_name="القنوات المستخدمة"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "delivery_results",
                    models.JSONField(default=dict, verbose_name="نتائج التسليم"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "مُرسل"),
                            ("failed", "فاشل"),
                            ("pending", "معلق"),
                            ("scheduled", "مجدول"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إشعار",
                "verbose_name_plural": "سجلات الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="الرسائل النصية"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات المدفوعة"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات داخل التطبيق"
                    ),
                ),
                (
                    "telegram_enabled",
                    models.BooleanField(default=False, verbose_name="Telegram"),
                ),
                (
                    "academic_notifications",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الأكاديمية"
                    ),
                ),
                (
                    "financial_notifications",
                    models.BooleanField(default=True, verbose_name="الإشعارات المالية"),
                ),
                (
                    "administrative_notifications",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الإدارية"
                    ),
                ),
                (
                    "security_notifications",
                    models.BooleanField(default=True, verbose_name="الإشعارات الأمنية"),
                ),
                (
                    "system_notifications",
                    models.BooleanField(default=False, verbose_name="إشعارات النظام"),
                ),
                (
                    "urgent_only",
                    models.BooleanField(default=False, verbose_name="العاجل فقط"),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(default=False, verbose_name="ساعات الهدوء"),
                ),
                (
                    "quiet_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="بداية الهدوء"
                    ),
                ),
                (
                    "quiet_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="نهاية الهدوء"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تفضيلات الإشعارات",
                "verbose_name_plural": "تفضيلات الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                            ("IN_APP", "In-App Notification"),
                            ("SYSTEM", "System Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic"),
                            ("FINANCIAL", "Financial"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("EMERGENCY", "Emergency"),
                            ("PROMOTIONAL", "Promotional"),
                            ("REMINDER", "Reminder"),
                            ("WELCOME", "Welcome"),
                            ("GRADUATION", "Graduation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=500)),
                ("message_template", models.TextField()),
                ("html_template", models.TextField(blank=True)),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variables that can be used in templates",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        default=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_opt_in", models.BooleanField(default=False)),
                ("language", models.CharField(default="en", max_length=10)),
                ("is_rtl", models.BooleanField(default=False)),
                ("send_immediately", models.BooleanField(default=True)),
                (
                    "batch_size",
                    models.IntegerField(
                        default=100,
                        help_text="Number of notifications to send per batch",
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum notifications per minute (0 = no limit)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates_enhanced",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="الاسم - إنجليزي"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "delivery_methods",
                    models.JSONField(default=list, verbose_name="طرق التوصيل"),
                ),
                (
                    "default_title_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="قالب العنوان"
                    ),
                ),
                (
                    "default_message_template",
                    models.TextField(blank=True, verbose_name="قالب الرسالة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "requires_user_consent",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب موافقة المستخدم"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نوع إشعار",
                "verbose_name_plural": "أنواع الإشعارات",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(max_length=100, verbose_name="معرف القالب"),
                ),
                ("recipients", models.JSONField(verbose_name="المستلمون")),
                ("variables", models.JSONField(default=dict, verbose_name="المتغيرات")),
                ("channels", models.JSONField(default=list, verbose_name="القنوات")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="وقت الإرسال المجدول"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدول"),
                            ("sent", "مُرسل"),
                            ("failed", "فاشل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="scheduled",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "delivery_results",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="نتائج التسليم"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال الفعلي"
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار مجدول",
                "verbose_name_plural": "الإشعارات المجدولة",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="UserDeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                ("token", models.TextField(verbose_name="رمز الجهاز")),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="معرف الجهاز"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="اسم الجهاز"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="إصدار التطبيق"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="آخر استخدام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "رمز جهاز مستخدم",
                "verbose_name_plural": "رموز أجهزة المستخدمين",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="الرسائل النصية"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات المدفوعة"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات داخل التطبيق"
                    ),
                ),
                (
                    "academic_notifications",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الأكاديمية"
                    ),
                ),
                (
                    "financial_notifications",
                    models.BooleanField(default=True, verbose_name="الإشعارات المالية"),
                ),
                (
                    "administrative_notifications",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الإدارية"
                    ),
                ),
                (
                    "security_notifications",
                    models.BooleanField(default=True, verbose_name="الإشعارات الأمنية"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تفضيلات إشعارات المستخدم",
                "verbose_name_plural": "تفضيلات إشعارات المستخدمين",
            },
        ),
        migrations.CreateModel(
            name="UserTelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="معرف المحادثة"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم المستخدم"
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(default=True, verbose_name="الإشعارات مفعلة"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="ar", max_length=5, verbose_name="اللغة المفضلة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثق"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الربط"),
                ),
                (
                    "last_interaction",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تفاعل"
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب Telegram",
                "verbose_name_plural": "حسابات Telegram",
            },
        ),
    ]
