# Generated by Django 4.2.16 on 2025-10-21 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        default="personal",
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="رابط الإجراء"),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نص الإجراء"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إشعار داخل التطبيق",
                "verbose_name_plural": "الإشعارات داخل التطبيق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        default="personal",
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="رابط الإجراء"),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نص الإجراء"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(max_length=100, verbose_name="معرف القالب"),
                ),
                (
                    "recipient_user_id",
                    models.CharField(max_length=50, verbose_name="معرف المستلم"),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد المستلم"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف المستلم"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "channels_used",
                    models.JSONField(default=list, verbose_name="القنوات المستخدمة"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "delivery_results",
                    models.JSONField(default=dict, verbose_name="نتائج التسليم"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "مُرسل"),
                            ("failed", "فاشل"),
                            ("pending", "معلق"),
                            ("scheduled", "مجدول"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="بيانات إضافية"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إشعار",
                "verbose_name_plural": "سجلات الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="الرسائل النصية"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات المدفوعة"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات داخل التطبيق"
                    ),
                ),
                (
                    "telegram_enabled",
                    models.BooleanField(default=False, verbose_name="Telegram"),
                ),
                (
                    "academic_notifications",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الأكاديمية"
                    ),
                ),
                (
                    "financial_notifications",
                    models.BooleanField(default=True, verbose_name="الإشعارات المالية"),
                ),
                (
                    "administrative_notifications",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الإدارية"
                    ),
                ),
                (
                    "security_notifications",
                    models.BooleanField(default=True, verbose_name="الإشعارات الأمنية"),
                ),
                (
                    "system_notifications",
                    models.BooleanField(default=False, verbose_name="إشعارات النظام"),
                ),
                (
                    "urgent_only",
                    models.BooleanField(default=False, verbose_name="العاجل فقط"),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(default=False, verbose_name="ساعات الهدوء"),
                ),
                (
                    "quiet_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="بداية الهدوء"
                    ),
                ),
                (
                    "quiet_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="نهاية الهدوء"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تفضيلات الإشعارات",
                "verbose_name_plural": "تفضيلات الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="معرف القالب"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القالب")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "أكاديمي"),
                            ("financial", "مالي"),
                            ("administrative", "إداري"),
                            ("security", "أمني"),
                            ("system", "النظام"),
                            ("personal", "شخصي"),
                            ("emergency", "طوارئ"),
                        ],
                        max_length=15,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=255, verbose_name="قالب العنوان"),
                ),
                ("message_template", models.TextField(verbose_name="قالب الرسالة")),
                (
                    "html_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="قالب HTML"
                    ),
                ),
                (
                    "required_variables",
                    models.JSONField(default=list, verbose_name="المتغيرات المطلوبة"),
                ),
                (
                    "default_channels",
                    models.JSONField(default=list, verbose_name="القنوات الافتراضية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قالب إشعار",
                "verbose_name_plural": "قوالب الإشعارات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(max_length=100, verbose_name="معرف القالب"),
                ),
                ("recipients", models.JSONField(verbose_name="المستلمون")),
                ("variables", models.JSONField(default=dict, verbose_name="المتغيرات")),
                ("channels", models.JSONField(default=list, verbose_name="القنوات")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("high", "عالي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="وقت الإرسال المجدول"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدول"),
                            ("sent", "مُرسل"),
                            ("failed", "فاشل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="scheduled",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "delivery_results",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="نتائج التسليم"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال الفعلي"
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار مجدول",
                "verbose_name_plural": "الإشعارات المجدولة",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="UserDeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                ("token", models.TextField(verbose_name="رمز الجهاز")),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="معرف الجهاز"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="اسم الجهاز"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="إصدار التطبيق"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="آخر استخدام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "رمز جهاز مستخدم",
                "verbose_name_plural": "رموز أجهزة المستخدمين",
            },
        ),
        migrations.CreateModel(
            name="UserTelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="معرف المحادثة"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم المستخدم"
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(default=True, verbose_name="الإشعارات مفعلة"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="ar", max_length=5, verbose_name="اللغة المفضلة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثق"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الربط"),
                ),
                (
                    "last_interaction",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تفاعل"
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب Telegram",
                "verbose_name_plural": "حسابات Telegram",
            },
        ),
    ]
