# Generated by Django 4.2.16 on 2025-10-29 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم - عربي"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="الاسم - إنجليزي"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "delivery_methods",
                    models.JSONField(default=list, verbose_name="طرق التوصيل"),
                ),
                (
                    "default_title_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="قالب العنوان"
                    ),
                ),
                (
                    "default_message_template",
                    models.TextField(blank=True, verbose_name="قالب الرسالة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "requires_user_consent",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب موافقة المستخدم"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نوع إشعار",
                "verbose_name_plural": "أنواع الإشعارات",
                "ordering": ["name_ar"],
            },
        ),
    ]
